-- ============================================================
-- BU DOSYA ARTIK ŞEMA KAYNAĞI DEĞİL.
--
-- Tek doğruluk kaynağı: supabase/migrations/ (sıralı, numaralı).
--   supabase db push          → uzak projeye uygula
--   supabase db reset         → yerel Supabase'i migration'lardan kur
--
-- Eski içerik (base tablolar + ilk RLS politikaları) 2026-09 güvenlik
-- denetiminde kaldırıldı: `0008_harden_invite_rls.sql` ile kapatılmış
-- zafiyetli davet/ortaklık politikalarını ve `search_path`'siz
-- SECURITY DEFINER fonksiyonunu hâlâ içeriyordu. Yeni bir ortam bu dosyayla
-- başlatılıp 0008 koşulmadan bırakılırsa herhangi bir kullanıcı canlı
-- davetleri listeleyip başkasının portföyünü okuyabiliyordu.
--
-- Base tabloların tanımı için: git geçmişi (`git log -- supabase_schema.sql`)
-- ya da `supabase db dump --schema public`.
-- ============================================================
