/// ABD hisse ve ETF kataloğu — Yahoo sembolü → şirket/fon adı.
///
/// ## Neden statik (v1, 2026-10-08, bayrak `abd_hisse`)
/// Türk bireysel yatırımcının en çok tuttuğu ABD kâğıtları: büyük şirketler,
/// S&P 500 öncüleri, popüler ETF'ler ve aracı kurum uygulamalarında öne
/// çıkan adlar. Seçicinin ve aramanın ağ beklemeden açılması için uygulama
/// içinde durur. Listede olmayan sembol serbest yazılır (`abdSembolu`) ve
/// yine Yahoo'dan fiyatlanır — liste bir SINIR değil, kısayoldur.
///
/// Sunucu kataloğu (nasdaqtrader günlük sembol listesi → tablo) sonraki
/// adımdır; o gelince bu liste aramada "popüler" önceliği olarak kalır.
///
/// ## Sembol biçimi
/// Yahoo'nun biçimi: sınıf hisseleri TİREYLE (`BRK-B`, `BF-B`), noktayla
/// değil — `BRK.B` Yahoo'da bulunmaz, fiyatsız lot doğardı. Yalnız şu an
/// işlem gören ve sembolünden emin olunanlar listededir: birleşme/isim
/// değişikliğiyle sembolü kalkan ya da değişen kâğıtlar (ör. Barrick'in
/// `GOLD` → `B` geçişi) bilerek dışarıda.
const Map<String, String> abdHisseleri = {
  // ── Teknoloji — büyükler ──────────────────────────────────────────────
  'AAPL': 'Apple',
  'MSFT': 'Microsoft',
  'NVDA': 'NVIDIA',
  'GOOGL': 'Alphabet (A)',
  'GOOG': 'Alphabet (C)',
  'AMZN': 'Amazon',
  'META': 'Meta Platforms',
  'TSLA': 'Tesla',
  'AVGO': 'Broadcom',
  'ORCL': 'Oracle',
  'NFLX': 'Netflix',
  'CRM': 'Salesforce',
  'ADBE': 'Adobe',
  'CSCO': 'Cisco Systems',
  'IBM': 'IBM',
  'INTU': 'Intuit',
  'NOW': 'ServiceNow',
  // ── Yarı iletken ──────────────────────────────────────────────────────
  'AMD': 'Advanced Micro Devices',
  'INTC': 'Intel',
  'QCOM': 'Qualcomm',
  'TXN': 'Texas Instruments',
  'MU': 'Micron Technology',
  'AMAT': 'Applied Materials',
  'LRCX': 'Lam Research',
  'KLAC': 'KLA',
  'ADI': 'Analog Devices',
  'MRVL': 'Marvell Technology',
  'NXPI': 'NXP Semiconductors',
  'ON': 'ON Semiconductor',
  'ARM': 'Arm Holdings',
  'TSM': 'Taiwan Semiconductor (TSMC)',
  'ASML': 'ASML Holding',
  'SMCI': 'Super Micro Computer',
  // ── Yazılım, internet, platform ───────────────────────────────────────
  'PLTR': 'Palantir Technologies',
  'PANW': 'Palo Alto Networks',
  'CRWD': 'CrowdStrike',
  'SNOW': 'Snowflake',
  'DDOG': 'Datadog',
  'NET': 'Cloudflare',
  'ZS': 'Zscaler',
  'MDB': 'MongoDB',
  'ANET': 'Arista Networks',
  'DELL': 'Dell Technologies',
  'HPQ': 'HP',
  'SHOP': 'Shopify',
  'UBER': 'Uber Technologies',
  'ABNB': 'Airbnb',
  'DASH': 'DoorDash',
  'SPOT': 'Spotify',
  'SNAP': 'Snap',
  'PINS': 'Pinterest',
  'RBLX': 'Roblox',
  'RDDT': 'Reddit',
  'APP': 'AppLovin',
  'SAP': 'SAP',
  'SONY': 'Sony Group',
  // ── Fintek ve kripto bağlantılı ───────────────────────────────────────
  'PYPL': 'PayPal',
  'COIN': 'Coinbase',
  'MSTR': 'Strategy',
  'HOOD': 'Robinhood Markets',
  'SOFI': 'SoFi Technologies',
  'AFRM': 'Affirm',
  'UPST': 'Upstart',
  'MARA': 'MARA Holdings',
  'RIOT': 'Riot Platforms',
  // ── Elektrikli araç ve otomotiv ───────────────────────────────────────
  'RIVN': 'Rivian Automotive',
  'LCID': 'Lucid Group',
  'NIO': 'NIO',
  'XPEV': 'XPeng',
  'LI': 'Li Auto',
  'F': 'Ford Motor',
  'GM': 'General Motors',
  'TM': 'Toyota Motor',
  // ── Çin ADR ───────────────────────────────────────────────────────────
  'BABA': 'Alibaba Group',
  'JD': 'JD.com',
  'PDD': 'PDD Holdings',
  'BIDU': 'Baidu',
  // ── Finans ────────────────────────────────────────────────────────────
  'BRK-B': 'Berkshire Hathaway (B)',
  'JPM': 'JPMorgan Chase',
  'BAC': 'Bank of America',
  'WFC': 'Wells Fargo',
  'C': 'Citigroup',
  'GS': 'Goldman Sachs',
  'MS': 'Morgan Stanley',
  'V': 'Visa',
  'MA': 'Mastercard',
  'AXP': 'American Express',
  'BLK': 'BlackRock',
  'SCHW': 'Charles Schwab',
  // ── Sağlık ────────────────────────────────────────────────────────────
  'LLY': 'Eli Lilly',
  'UNH': 'UnitedHealth Group',
  'JNJ': 'Johnson & Johnson',
  'NVO': 'Novo Nordisk',
  'PFE': 'Pfizer',
  'MRK': 'Merck & Co.',
  'ABBV': 'AbbVie',
  'TMO': 'Thermo Fisher Scientific',
  'ABT': 'Abbott Laboratories',
  'AMGN': 'Amgen',
  'GILD': 'Gilead Sciences',
  'BMY': 'Bristol-Myers Squibb',
  'MRNA': 'Moderna',
  'ISRG': 'Intuitive Surgical',
  'CVS': 'CVS Health',
  // ── Tüketim ───────────────────────────────────────────────────────────
  'WMT': 'Walmart',
  'COST': 'Costco',
  'KO': 'Coca-Cola',
  'PEP': 'PepsiCo',
  'PG': 'Procter & Gamble',
  'MCD': "McDonald's",
  'SBUX': 'Starbucks',
  'NKE': 'Nike',
  'DIS': 'Walt Disney',
  'HD': 'Home Depot',
  'LOW': "Lowe's",
  'TGT': 'Target',
  'CMG': 'Chipotle Mexican Grill',
  'BKNG': 'Booking Holdings',
  'MAR': 'Marriott International',
  'LULU': 'Lululemon Athletica',
  'PM': 'Philip Morris International',
  'MO': 'Altria Group',
  'MDLZ': 'Mondelez International',
  'CL': 'Colgate-Palmolive',
  'EL': 'Estée Lauder',
  'BF-B': 'Brown-Forman (B)',
  // ── Enerji ────────────────────────────────────────────────────────────
  'XOM': 'Exxon Mobil',
  'CVX': 'Chevron',
  'COP': 'ConocoPhillips',
  'OXY': 'Occidental Petroleum',
  'SLB': 'SLB',
  'SHEL': 'Shell',
  'BP': 'BP',
  'NEE': 'NextEra Energy',
  // ── Sanayi, savunma, ulaşım ───────────────────────────────────────────
  'BA': 'Boeing',
  'CAT': 'Caterpillar',
  'DE': 'Deere & Company',
  'GE': 'GE Aerospace',
  'GEV': 'GE Vernova',
  'HON': 'Honeywell',
  'LMT': 'Lockheed Martin',
  'RTX': 'RTX',
  'NOC': 'Northrop Grumman',
  'UPS': 'United Parcel Service',
  'FDX': 'FedEx',
  'UNP': 'Union Pacific',
  'MMM': '3M',
  // ── İletişim ──────────────────────────────────────────────────────────
  'T': 'AT&T',
  'VZ': 'Verizon',
  'TMUS': 'T-Mobile US',
  // ── Madencilik ve gayrimenkul ─────────────────────────────────────────
  'NEM': 'Newmont',
  'FCX': 'Freeport-McMoRan',
  'O': 'Realty Income',
  'AMT': 'American Tower',
  'PLD': 'Prologis',
  // ── ETF — geniş piyasa ────────────────────────────────────────────────
  'SPY': 'SPDR S&P 500 ETF',
  'VOO': 'Vanguard S&P 500 ETF',
  'IVV': 'iShares Core S&P 500 ETF',
  'VTI': 'Vanguard Total Stock Market ETF',
  'QQQ': 'Invesco QQQ (Nasdaq-100)',
  'QQQM': 'Invesco Nasdaq-100 ETF',
  'DIA': 'SPDR Dow Jones Industrial Average ETF',
  'IWM': 'iShares Russell 2000 ETF',
  'VUG': 'Vanguard Growth ETF',
  'VTV': 'Vanguard Value ETF',
  'VGT': 'Vanguard Information Technology ETF',
  // ── ETF — temettü ─────────────────────────────────────────────────────
  'SCHD': 'Schwab US Dividend Equity ETF',
  'VYM': 'Vanguard High Dividend Yield ETF',
  'VIG': 'Vanguard Dividend Appreciation ETF',
  'JEPI': 'JPMorgan Equity Premium Income ETF',
  'JEPQ': 'JPMorgan Nasdaq Equity Premium Income ETF',
  // ── ETF — sektör ve tema ──────────────────────────────────────────────
  'XLK': 'Technology Select Sector SPDR',
  'XLF': 'Financial Select Sector SPDR',
  'XLE': 'Energy Select Sector SPDR',
  'XLV': 'Health Care Select Sector SPDR',
  'XLY': 'Consumer Discretionary Select Sector SPDR',
  'XLP': 'Consumer Staples Select Sector SPDR',
  'XLI': 'Industrial Select Sector SPDR',
  'XLU': 'Utilities Select Sector SPDR',
  'SOXX': 'iShares Semiconductor ETF',
  'SMH': 'VanEck Semiconductor ETF',
  'ARKK': 'ARK Innovation ETF',
  'VNQ': 'Vanguard Real Estate ETF',
  // ── ETF — kaldıraçlı ──────────────────────────────────────────────────
  'TQQQ': 'ProShares UltraPro QQQ (3x)',
  'SQQQ': 'ProShares UltraPro Short QQQ (-3x)',
  'SOXL': 'Direxion Daily Semiconductor Bull 3x',
  // ── ETF — uluslararası ────────────────────────────────────────────────
  'VEA': 'Vanguard FTSE Developed Markets ETF',
  'VWO': 'Vanguard FTSE Emerging Markets ETF',
  'VXUS': 'Vanguard Total International Stock ETF',
  'EEM': 'iShares MSCI Emerging Markets ETF',
  'EFA': 'iShares MSCI EAFE ETF',
  'FXI': 'iShares China Large-Cap ETF',
  'KWEB': 'KraneShares CSI China Internet ETF',
  'INDA': 'iShares MSCI India ETF',
  'EWJ': 'iShares MSCI Japan ETF',
  'EWZ': 'iShares MSCI Brazil ETF',
  // ── ETF — tahvil ──────────────────────────────────────────────────────
  'BND': 'Vanguard Total Bond Market ETF',
  'AGG': 'iShares Core US Aggregate Bond ETF',
  'TLT': 'iShares 20+ Year Treasury Bond ETF',
  'IEF': 'iShares 7-10 Year Treasury Bond ETF',
  'SHY': 'iShares 1-3 Year Treasury Bond ETF',
  'SGOV': 'iShares 0-3 Month Treasury Bond ETF',
  'BIL': 'SPDR Bloomberg 1-3 Month T-Bill ETF',
  'LQD': 'iShares iBoxx Investment Grade Corporate Bond ETF',
  'HYG': 'iShares iBoxx High Yield Corporate Bond ETF',
  // ── ETF — emtia ve kripto ─────────────────────────────────────────────
  'GLD': 'SPDR Gold Shares',
  'IAU': 'iShares Gold Trust',
  'SLV': 'iShares Silver Trust',
  'GDX': 'VanEck Gold Miners ETF',
  'IBIT': 'iShares Bitcoin Trust ETF',
};

/// Kullanıcının serbest yazdığı sembolü Yahoo biçimine çevirir: büyük harf,
/// boşluksuz, sınıf ayracı nokta → tire (`brk.b` → `BRK-B`).
///
/// Neden: aracı kurum ekranları ve haber siteleri sınıf hissesini `BRK.B`
/// yazar; Yahoo'da o sembol yoktur ve lot fiyatsız kalırdı.
String abdSembolu(String metin) =>
    metin.trim().toUpperCase().replaceAll(RegExp(r'\s+'), '').replaceAll('.', '-');
