// BIST'te işlem gören hisseler — Yahoo sembolü → şirket adı.
//
// ── Neden ayrı dosya ve neden bu kadar uzun (2026-10-10) ─────────────────────
// Liste `asset_categories.dart` içinde elle yazılmıştı (322 sembol). Kullanıcı
// bildirimi: "tüm BIST100 hisseleri yok". Ölçüm (TradingView tarayıcısı, KAP,
// Yahoo; GitHub Actions runner'ında, `tool/bist_evren_olc.py`): borsada 626
// adi hisse + 4 yatırım ortaklığı işlem görüyor; BIST 100'ün 24'ü (AYGAZ,
// ENKAI, FENER, ASTOR, TRALT…) listede yoktu, 20 sembol de artık işlem
// görmüyordu (KOZAL→TRALT, KOZAA→TRMET, IPEKE→TRENJ, QNBFB→QNBTR, ENKA
// aslında ENKAI). Liste artık borsanın TAMAMI; elle seçki yapılmaz.
//
// Kural: yeni hisse (halka arz) ya da kod değişikliği olunca listeyi
// `BIST hisse evreni` iş akışıyla yeniden ölç, elle tahmin yazma. Var olan
// adlar korunur (kullanıcı onları gördü); yeni adlar KAP unvanından kısaltılır.
//
// Dışarıda kalanlar, bilerek: borsa yatırım fonları (BYF/ETF — fon, hisse
// değil) ve Darphane sertifikaları ALTIN/DMLKT (Yahoo fiyat vermiyor; "ALTIN"
// hisse kodu sayılsaydı ekstrede altın satırı hisse diye okunurdu).
//
// İsim `bist100StocksMap` geriye dönük uyumluluk için kaldı; kapsam BIST 100
// ile sınırlı DEĞİLDİR (GSDHO regresyonu, `bist_stock_coverage_test`).

/// Borsada bugün işlem gören tüm hisseler (alfabetik).
const bist100StocksMap = <String, String>{
  'A1CAP.IS': 'A1 Capital Yatırım Menkul Değerler',
  'A1YEN.IS': 'A1 Yenilenebilir Enerji',
  'AAGYO.IS': 'Ağaoğlu Avrasya GYO',
  'ACSEL.IS': 'Acıselsan Acıpayam Selüloz',
  'ADEL.IS': 'Adel Kalemcilik',
  'ADESE.IS': 'Adese Gayrimenkul',
  'ADGYO.IS': 'Adra GYO',
  'AEFES.IS': 'Anadolu Efes',
  'AFYON.IS': 'Afyon Çimento',
  'AGESA.IS': 'Agesa Hayat ve Emeklilik',
  'AGHOL.IS': 'AG Anadolu Grubu Holding',
  'AGROT.IS': 'Agrotech Yüksek Teknoloji',
  'AGYO.IS': 'Atakule GYO',
  'AHGAZ.IS': 'Ahlatcı Doğal Gaz Dağıtım Enerji',
  'AHSGY.IS': 'Ahes GYO',
  'AKBNK.IS': 'Akbank',
  'AKCNS.IS': 'Akçansa Çimento',
  'AKENR.IS': 'Ak Enerji',
  'AKFGY.IS': 'Akfen GYO',
  'AKFIS.IS': 'Akfen İnşaat Turizm',
  'AKFYE.IS': 'Akfen Yenilenebilir Enerji',
  'AKGRT.IS': 'Aksigorta',
  'AKHAN.IS': 'Akhan Un Fabrikası Ve Tarım Ürünleri Gıda',
  'AKMGY.IS': 'Akmerkez GYO',
  'AKSA.IS': 'Aksa Akrilik',
  'AKSEN.IS': 'Aksa Enerji',
  'AKSGY.IS': 'Akiş GYO',
  'AKSUE.IS': 'Aksu Enerji',
  'AKYHO.IS': 'Akdeniz Yatırım Holding',
  'ALARK.IS': 'Alarko Holding',
  'ALBRK.IS': 'Albaraka Türk',
  'ALBTN.IS': 'Albayrak Hazır Beton',
  'ALCAR.IS': 'Alarko Carrıer',
  'ALCTL.IS': 'Alcatel Lucent Teleteknik',
  'ALFAS.IS': 'Alfa Solar Enerji',
  'ALGYO.IS': 'Alarko GYO',
  'ALKA.IS': 'Alkim Kağıt',
  'ALKIM.IS': 'Alkim Alkali Kimya',
  'ALKLC.IS': 'Altınkılıç Gıda Ve Süt',
  'ALTNY.IS': 'Altınay Savunma Teknolojileri',
  'ALVES.IS': 'Alves Kablo',
  'ANELE.IS': 'Anel Elektrik',
  'ANGEN.IS': 'Anatolia Tanı Ve Biyoteknoloji Ürünleri Araştırma Geliştirme',
  'ANHYT.IS': 'Anadolu Hayat Emeklilik',
  'ANSGR.IS': 'Anadolu Sigorta',
  'ARASE.IS': 'Aras Elektrik Dağıtım',
  'ARCLK.IS': 'Arçelik',
  'ARDYZ.IS': 'ARD Bilişim Teknolojileri',
  'ARENA.IS': 'Arena Bilgisayar',
  'ARFYE.IS': 'Arf Bio Yenilenebilir Enerji',
  'ARMGD.IS': 'Armada Gıda',
  'ARSAN.IS': 'Arsan Tekstil',
  'ARTMS.IS': 'Artemis Halı',
  'ARZUM.IS': 'Arzum Elektrikli Ev Aletleri',
  'ASELS.IS': 'Aselsan',
  'ASGYO.IS': 'Asce GYO',
  'ASTOR.IS': 'Astor Enerji',
  'ASUZU.IS': 'Anadolu Isuzu',
  'ATAGY.IS': 'Ata GYO',
  'ATAKP.IS': 'Atakey Patates',
  'ATATP.IS': 'ATA Teknoloji Platformu',
  'ATATR.IS': 'Ata Turizm İşletmecilik Taşımacılık Madencilik Kuyumculuk',
  'ATEKS.IS': 'Akın Tekstil',
  'ATLAS.IS': 'Atlas Menkul Kıymetler Yatırım Ortaklığı',
  'ATSYH.IS': 'Atlantis Yatırım Holding',
  'AVGYO.IS': 'Avrasya GYO',
  'AVHOL.IS': 'Avrupa Yatırım Holding',
  'AVOD.IS': 'A.V.O.D. Gıda',
  'AVPGY.IS': 'Avrupakent GYO',
  'AVTUR.IS': 'Avrasya Petrol Turistik',
  'AYCES.IS': 'Altınyunus Çeşme',
  'AYDEM.IS': 'Aydem Yenilenebilir Enerji',
  'AYEN.IS': 'Ayen Enerji',
  'AYES.IS': 'Ayes Çelik Hasır Ve Çit',
  'AYGAZ.IS': 'Aygaz',
  'AZTEK.IS': 'Aztek Teknoloji Ürünleri',
  'BAGFS.IS': 'Bagfaş Bandırma Gübre',
  'BAHKM.IS': 'Bahadır Kimya',
  'BAKAB.IS': 'Bak Ambalaj',
  'BALAT.IS': 'Balatacılar Balatacılık',
  'BALSU.IS': 'Balsu Gıda',
  'BANVT.IS': 'Banvit',
  'BARMA.IS': 'Barem Ambalaj',
  'BASCM.IS': 'Baştaş Çimento',
  'BASGZ.IS': 'Başkent Doğalgaz',
  'BAYRK.IS': 'Bayrak EBT',
  'BEGYO.IS': 'Batı EGE GYO',
  'BERA.IS': 'Bera Holding',
  'BESLR.IS': 'Besler Gıda Ve Kimya',
  'BESTE.IS': 'Best Brands Grup Enerji',
  'BETAE.IS': 'Beta Enerji Ve Teknoloji',
  'BEYAZ.IS': 'Beyaz Filo',
  'BFREN.IS': 'Bosch Fren Sistemleri',
  'BIENY.IS': 'Bien Yapı Ürünleri Sanayi Turizm',
  'BIGCH.IS':
      'Büyük Şefler Gıda Turizm Tekstil Danışmanlık Organizasyon Eğitim',
  'BIGEN.IS': 'Birleşim Grup Enerji',
  'BIGTK.IS': 'Big Medya Teknoloji',
  'BIMAS.IS': 'BİM Mağazalar',
  'BINBN.IS': 'Bin Ulaşım Ve Akıllı Şehir Teknolojileri',
  'BINHO.IS': 'Bin Holding',
  'BIOEN.IS': 'Biotrend Enerji',
  'BIZIM.IS': 'Bizim Toptan Satış',
  'BJKAS.IS': 'Beşiktaş Futbol',
  'BKRGY.IS': 'Bakırcı GYO',
  'BLCYT.IS': 'Bilici Yatırım',
  'BLUME.IS': 'Blume Metal Kimya',
  'BMSCH.IS': 'BMS Çelik Hasır',
  'BMSTL.IS': 'BMS Birleşik Metal',
  'BNTAS.IS': 'Bantaş Ambalaj',
  'BOBET.IS': 'Boğaziçi Beton',
  'BORLS.IS': 'Borlease Otomotiv',
  'BORSK.IS': 'Bor Şeker',
  'BOSSA.IS': 'Bossa Ticaret',
  'BRISA.IS': 'Brisa Bridgestone',
  'BRKO.IS': 'Birko Mensucat',
  'BRKSN.IS': 'Berkosan Yalıtım',
  'BRKVY.IS': 'Birikim Varlık Yönetim',
  'BRLSM.IS': 'Birleşim Mühendislik Isıtma Soğutma Havalandırma',
  'BRMEN.IS': 'Birlik Mensucat Ticaret Ve Sanayi İşletmesi',
  'BRSAN.IS': 'Borusan Birleşik Boru Fabrikaları',
  'BRYAT.IS': 'Borusan',
  'BSOKE.IS': 'Batısöke Çimento',
  'BTCIM.IS': 'Batıçim Batı Anadolu',
  'BUCIM.IS': 'Bursa Çimento',
  'BULGS.IS': 'Bulls Girişim Sermayesi Yatırım Ortaklığı',
  'BURCE.IS': 'Burçelik',
  'BURVA.IS': 'Burçelik Vana',
  'BVSAN.IS': 'Bülbüloğlu Vinç',
  'BYDNR.IS': 'Baydöner Restoranları',
  'CANTE.IS': 'Çan2 Termik',
  'CASA.IS': 'Casa Emtia Petrol Kimyevi Ve Türevleri',
  'CATES.IS': 'Çates Elektrik',
  'CCOLA.IS': 'Coca-Cola İçecek',
  'CELHA.IS': 'Çelik Halat Ve Tel',
  'CEMAS.IS': 'Çemaş Döküm',
  'CEMTS.IS': 'Çemtaş Çelik',
  'CEMZY.IS': 'Cem Zeytin',
  'CEOEM.IS': 'Ceo Event Medya',
  'CGCAM.IS': 'Çağdaş Cam',
  'CIMSA.IS': 'Çimsa Çimento',
  'CITAS.IS': 'Çitlekçi Mağazacılık',
  'CLEBI.IS': 'Çelebi Havacılık',
  'CMBTN.IS': 'Çimbeton',
  'CMENT.IS': 'Çimentaş',
  'CONSE.IS': 'Consus Enerji',
  'COSMO.IS': 'Cosmos Yatırım Holding',
  'CRDFA.IS': 'Creditwest Faktoring',
  'CRFSA.IS': 'Carrefoursa Carrefour Sabancı Ticaret Merkezi',
  'CUSAN.IS': 'Çuhadaroğlu Metal',
  'CVKMD.IS': 'CVK Maden İşletmeleri',
  'CWENE.IS': 'CW Enerji',
  'DAGI.IS': 'Dagi Yatırım Holding',
  'DAPGM.IS': 'Dap Gayrimenkul Geliştirme',
  'DARDL.IS': 'Dardanel Önentaş',
  'DCTTR.IS': 'DCT Trading',
  'DENGE.IS': 'Denge Yatırım Holding',
  'DERHL.IS': 'Derlüks Yatırım Holding',
  'DERIM.IS': 'Derimod Konfeksiyon Ayakkabı Deri',
  'DESA.IS': 'Desa Deri',
  'DESPC.IS': 'Despec Bilgisayar',
  'DEVA.IS': 'Deva Holding',
  'DGATE.IS': 'Datagate Bilgisayar',
  'DGGYO.IS': 'Doğuş GYO',
  'DGNMO.IS': 'Doğan Trend Otomotiv',
  'DIRIT.IS': 'Diriteks Diriliş Tekstil',
  'DITAS.IS': 'Ditaş Doğan',
  'DMRGD.IS': 'DMR Unlu Mamuller Üretim Gıda Toptan Perakende',
  'DMSAS.IS': 'Demisaş Döküm',
  'DNISI.IS': 'Dinamik Isı Makina Yalıtım Malzemeleri',
  'DOAS.IS': 'Doğuş Otomotiv',
  'DOCO.IS': 'Do \\u0026 Co Aktıengesellschaft',
  'DOFER.IS': 'Dofer Yapı Malzemeleri',
  'DOFRB.IS': 'Dof Robotik',
  'DOGUB.IS': 'Doğusan Boru',
  'DOHOL.IS': 'Doğan Holding',
  'DOKTA.IS': 'Döktaş Dökümcülük',
  'DSTKF.IS': 'Destek Finans Faktoring',
  'DUNYH.IS': 'Dünya Holding',
  'DURDO.IS': 'Duran Doğan Basım',
  'DURKN.IS': 'Durukan Şekerleme',
  'DYOBY.IS': 'DYO Boya',
  'DZGYO.IS': 'Deniz GYO',
  'EBEBK.IS': 'Ebebek Mağazacılık',
  'ECILC.IS': 'Eczacıbaşı İlaç',
  'ECOGR.IS': 'Ecogreen Enerji Holding',
  'ECZYT.IS': 'Eczacıbaşı Yatırım',
  'EDATA.IS': 'E-data Teknoloji',
  'EDIP.IS': 'Edip Gayrimenkul',
  'EFOR.IS': 'Efor',
  'EGEEN.IS': 'Ege Endüstri',
  'EGEGY.IS': 'Egeyapı Avrupa GYO',
  'EGEPO.IS': 'Ege Profil',
  'EGGUB.IS': 'Ege Gübre',
  'EGPRO.IS': 'EGE Profil',
  'EGSER.IS': 'EGE Seramik',
  'EKDMR.IS': 'Ekinciler Demir Ve Çelik',
  'EKGYO.IS': 'Emlak Konut GYO',
  'EKIM.IS': 'Ekim Turizm (Intercity)',
  'EKIZ.IS': 'Ekiz Kimya',
  'EKOS.IS': 'Ekos Teknoloji Ve Elektrik',
  'EKSUN.IS': 'Eksun Gıda Tarım',
  'ELITE.IS': 'Elite Naturel Organik Gıda',
  'EMKEL.IS': 'Emek Elektrik',
  'EMNIS.IS': 'Eminiş Ambalaj',
  'EMPAE.IS': 'Empa Elektronik',
  'ENDAE.IS': 'Enda Enerji Holding',
  'ENERY.IS': 'Enerya Enerji',
  'ENJSA.IS': 'Enerjisa Enerji',
  'ENKAI.IS': 'Enka',
  'ENPRA.IS': 'Enpara Bank',
  'ENSRI.IS': 'Ensari Sınai Yatırımlar',
  'ENTRA.IS': 'Ic Enterra Yenilenebilir Enerji',
  'EPLAS.IS': 'Egeplast EGE Plastik',
  'ERBOS.IS': 'Erbosan',
  'ERCB.IS': 'Erciyas Çelik Boru',
  'EREGL.IS': 'Ereğli Demir Çelik',
  'ERSU.IS': 'Ersu Meyve Ve Gıda',
  'ESCAR.IS': 'Escar Filo Kiralama',
  'ESCOM.IS': 'Escort Teknoloji',
  'ESEN.IS': 'Esenboğa Elektrik',
  'ETILR.IS': 'Etiler Gıda Ve Ticari Yatırımlar',
  'ETYAT.IS': 'Euro Trend Yatırım Ortaklığı',
  'EUHOL.IS': 'Euro Yatırım Holding',
  'EUKYO.IS': 'Euro Kapital Yatırım Ortaklığı',
  'EUPWR.IS': 'Europower Enerji',
  'EUREN.IS': 'Europen Endüstri',
  'EUYO.IS': 'Euro Menkul Kıymet Yatırım Ortaklığı',
  'EYGYO.IS': 'Eyg GYO',
  'FADE.IS': 'Fade Gıda',
  'FENER.IS': 'Fenerbahçe Futbol',
  'FLAP.IS': 'Flap Kongre Toplantı Hizmetleri Otomotiv Ve Turizm',
  'FMIZP.IS': 'Federal-Mogul İzmit Piston',
  'FONET.IS': 'Fonet Bilgi Teknolojileri',
  'FORMT.IS': 'Formet Metal Ve Cam',
  'FORTE.IS': 'Forte Bilgi İletişim Teknolojileri Ve Savunma',
  'FRIGO.IS': 'Frigo Pak Gıda',
  'FRMPL.IS': 'Formül Plastik Ve Metal',
  'FROTO.IS': 'Ford Otosan',
  'FZLGY.IS': 'Fuzul GYO',
  'GARAN.IS': 'Garanti BBVA',
  'GARFA.IS': 'Garanti Faktoring',
  'GATEG.IS': 'Gate Group Teknoloji Medya Ve Siber Güvenlik',
  'GEDIK.IS': 'Gedik Yatırım Menkul Değerler',
  'GEDZA.IS': 'Gediz Ambalaj',
  'GENIL.IS': 'Gen İlaç Ve Sağlık Ürünleri',
  'GENKM.IS': 'Gentaş Kimya',
  'GENTS.IS': 'Gentaş Genel Metal',
  'GEREL.IS': 'Gersan Elektrik',
  'GESAN.IS': 'Girişim Elektrik Sanayi Taahhüt',
  'GIPTA.IS': 'Gıpta Ofis Kırtasiye Ve Promosyon Ürünleri İmalat',
  'GLBMD.IS': 'Global Menkul Değerler',
  'GLCVY.IS': 'Gelecek Varlık Yönetimi',
  'GLRMK.IS': 'Gülermak Ağır Sanayi İnşaat Ve Taahhüt',
  'GLRYH.IS': 'Güler Yatırım Holding',
  'GLYHO.IS': 'Global Yatırım Holding',
  'GMTAS.IS': 'Gimat Mağazacılık',
  'GOKNR.IS': 'Göknur Gıda Maddeleri Enerji İmalat',
  'GOLDA.IS': 'Golda Gıda',
  'GOLTS.IS': 'Göltaş Çimento',
  'GOODY.IS': 'Goodyear Lastikleri',
  'GOZDE.IS': 'Gözde Girişim Sermayesi Yatırım Ortaklığı',
  'GRNYO.IS': 'Garanti Yatırım Ortaklığı',
  'GRSEL.IS': 'Gür-sel Turizm Taşımacılık Ve Servis',
  'GRTHO.IS': 'Graınturk Holding',
  'GSDDE.IS': 'GSD Denizcilik Gayrimenkul',
  'GSDHO.IS': 'GSD Holding',
  'GSRAY.IS': 'Galatasaray Sportif Sınai Ve Ticari Yatırımlar',
  'GUBRF.IS': 'Gübre Fabrikaları',
  'GUNDG.IS': 'Gündoğdu Gıda Süt Ürünleri',
  'GWIND.IS': 'Galata Wind Enerji',
  'GZNMI.IS': 'Gezinomi Seyahat Turizm',
  'HALKB.IS': 'Halkbank',
  'HATEK.IS': 'Hateks Hatay Tekstil İşletmeleri',
  'HATSN.IS': 'Hat-san Gemi İnşaa Bakım Onarım Deniz Nakliyat',
  'HDFGS.IS': 'Hedef Girişim Sermayesi Yatırım Ortaklığı',
  'HEDEF.IS': 'Hedef Holding',
  'HEKTS.IS': 'Hektaş Ticaret',
  'HKTM.IS': 'Hidropar Hareket Kontrol Teknolojileri Merkezi',
  'HLGYO.IS': 'Halk GYO',
  'HOROZ.IS': 'Horoz Lojistik Kargo',
  'HRKET.IS': 'Hareket Proje Taşımacılığı Ve Yük Mühendisliği',
  'HTTBT.IS': 'Hitit Bilgisayar',
  'HUBVC.IS': 'Hub Girişim Sermayesi Yatırım Ortaklığı',
  'HUNER.IS': 'Hun Yenilenebilir Enerji',
  'HURGZ.IS': 'Hürriyet Gazetecilik',
  'ICBCT.IS': 'ICBC Turkey Bank',
  'ICUGS.IS': 'Icu Girişim Sermayesi Yatırım Ortaklığı',
  'IDGYO.IS': 'İdealist GYO',
  'IEYHO.IS': 'Işıklar Enerji ve Yapı Holding',
  'IHAAS.IS': 'İhlas Haber Ajansı',
  'IHEVA.IS': 'İhlas Ev Aletleri İmalat',
  'IHGZT.IS': 'İhlas Gazetecilik',
  'IHLAS.IS': 'İhlas Holding',
  'IHLGM.IS': 'İhlas Gayrimenkul Proje Geliştirme',
  'IHYAY.IS': 'İhlas Yayın Holding',
  'IMASM.IS': 'İmaş Makina',
  'INDES.IS': 'İndeks Bilgisayar',
  'INFO.IS': 'İnfo Yatırım Menkul Değerler',
  'INGRM.IS': 'Ingram Micro Bilişim Sistemleri',
  'INTEK.IS': 'İnnosa Teknoloji',
  'INTEM.IS': 'İntema İnşaat',
  'INTET.IS': 'İntetra Teknoloji',
  'INVEO.IS': 'Inveo Yatırım Holding',
  'INVES.IS': 'Investco Holding',
  'ISBIR.IS': 'İşbir Holding',
  'ISBTR.IS': 'İş Bankası (B)',
  'ISCTR.IS': 'İş Bankası (C)',
  'ISDMR.IS': 'İskenderun Demir Çelik',
  'ISFIN.IS': 'İş Finansal Kiralama',
  'ISGSY.IS': 'İş Girişim Sermayesi Yatırım Ortaklığı',
  'ISGYO.IS': 'İş GYO',
  'ISKPL.IS': 'Işık Plastik',
  'ISMEN.IS': 'İş Yatırım Menkul Değerler',
  'ISSEN.IS': 'İşbir Sentetik Dokuma',
  'ISVEA.IS': 'İsvea Seramik',
  'ISYAT.IS': 'İş Yatırım Ortaklığı',
  'IZENR.IS': 'İzdemir Enerji Elektrik',
  'IZFAS.IS': 'İzmir Fırça',
  'IZINV.IS': 'İz Yatırım Holding',
  'IZMDC.IS': 'İzmir Demir Çelik',
  'JANTS.IS': 'Jantsa Jant Sanayi',
  'KAPLM.IS': 'Kaplamin Ambalaj',
  'KARCL.IS': 'Kardemir Çelik',
  'KAREL.IS': 'Karel Elektronik',
  'KARSN.IS': 'Karsan Otomotiv',
  'KARTN.IS': 'Kartonsan Karton',
  'KATMR.IS': 'Katmerciler Ekipman',
  'KAYSE.IS': 'Kayseri Şeker Fabrikası',
  'KBORU.IS': 'Kuzey Boru',
  'KCAER.IS': 'Kocaer Çelik',
  'KCHOL.IS': 'Koç Holding',
  'KENT.IS': 'Kent Gıda Maddeleri',
  'KERVN.IS': 'Kervansaray Yatırım Holding',
  'KFEIN.IS': 'Kafein Yazılım',
  'KGYO.IS': 'Koray GYO',
  'KIMMR.IS': 'Kim Mağazacılık',
  'KLGYO.IS': 'Kiler GYO',
  'KLKIM.IS': 'Kalekim Kimyevi Maddeler',
  'KLMSN.IS': 'Klimasan Klima',
  'KLNMA.IS': 'Kalkınma ve Yatırım Bankası',
  'KLRHO.IS': 'Kiler Holding',
  'KLSER.IS': 'Kaleseramik Çanakkale Kalebodur Seramik',
  'KLSYN.IS': 'Koleksiyon Mobilya',
  'KLYPV.IS': 'Kalyon Güneş Teknolojileri',
  'KMPUR.IS': 'Kimteks Poliüretan',
  'KNFRT.IS': 'Konfrut Gıda',
  'KOCMT.IS': 'Koç Metalurji',
  'KONKA.IS': 'Konya Kağıt',
  'KONTR.IS': 'Kontrolmatik Teknoloji',
  'KONYA.IS': 'Konya Çimento',
  'KOPOL.IS': 'Koza Polyester',
  'KORDS.IS': 'Kordsa Teknik',
  'KOTON.IS': 'Koton Mağazacılık Tekstil',
  'KPEKS.IS': 'Kapeks Kimya',
  'KRDMA.IS': 'Kardemir Karabük Demir Çelik',
  'KRDMB.IS': 'Kardemir Karabük Demir Çelik',
  'KRDMD.IS': 'Kardemir (D)',
  'KRGYO.IS': 'Körfez GYO',
  'KRONT.IS': 'Kron Teknoloji',
  'KRPLS.IS': 'Koroplast Temizlik Ambalaj Ürünleri',
  'KRSTL.IS': 'Kristal Kola',
  'KRTEK.IS': 'Karsu Tekstil',
  'KRVGD.IS': 'Kervan Gıda',
  'KSTUR.IS': 'Kuştur Kuşadası Turizm Endüstrisi',
  'KTLEV.IS': 'Katılımevim Tasarruf Finansman',
  'KTSKR.IS': 'Kütahya Şeker',
  'KUTPO.IS': 'Kütahya Porselen',
  'KUVVA.IS': 'Kuvva Gıda',
  'KUYAS.IS': 'Kuyaş',
  'KZBGY.IS': 'Kızılbük GYO',
  'KZGYO.IS': 'Kuzugrup GYO',
  'LIDER.IS': 'LDR Turizm',
  'LIDFA.IS': 'Lider Faktoring',
  'LILAK.IS': 'Lila Kağıt',
  'LINK.IS': 'Link Bilgisayar',
  'LKMNH.IS': 'Lokman Hekim Sağlık',
  'LMKDC.IS': 'Limak Doğu Anadolu Çimento',
  'LOGO.IS': 'Logo Yazılım',
  'LRSHO.IS': 'Loras Holding',
  'LUKSK.IS': 'Lüks Kadife',
  'LXGYO.IS': 'Luxera GYO',
  'LYDHO.IS': 'Lydia Holding',
  'LYDYE.IS': 'Lydia Yeşil Enerji Kaynakları',
  'MAALT.IS': 'Marmaris Altınyunus',
  'MACKO.IS': 'Mackolik İnternet',
  'MAGEN.IS': 'Margün Enerji',
  'MAKIM.IS': 'Makim Makina Teknolojileri',
  'MAKTK.IS': 'Makina Takım Endüstrisi',
  'MANAS.IS': 'Manas Enerji Yönetimi',
  'MARBL.IS': 'TUREKS Turunç Madencilik İç',
  'MARMR.IS': 'Marmara Holding',
  'MARTI.IS': 'Martı Otel İşletmeleri',
  'MASFN.IS': 'Masfen Enerji',
  'MAVI.IS': 'Mavi Giyim',
  'MCARD.IS': 'Metropal Kurumsal Hizmetler',
  'MEDTR.IS': 'Meditera Tıbbi Malzeme',
  'MEGAP.IS': 'Mega Polietilen Köpük',
  'MEGMT.IS': 'Mega Metal',
  'MEKAG.IS': 'Meka Global Makine İmalat',
  'MEPET.IS': 'Mepet Metro Petrol',
  'MERCN.IS': 'Mercan Kimya',
  'MERIT.IS': 'Merit Turizm Yatırım Ve İşletme',
  'MERKO.IS': 'Merko Gıda',
  'METEN.IS': 'Metgün Enerji',
  'METRO.IS': 'Metro Holding',
  'MEYSU.IS': 'Meysu Gıda',
  'MGROS.IS': 'Migros Ticaret',
  'MHRGY.IS': 'MHR GYO',
  'MIATK.IS': 'Mia Teknoloji',
  'MMCAS.IS': 'MMC Sanayi Ve Ticari Yatırımlar',
  'MNDRS.IS': 'Menderes Tekstil',
  'MNDTR.IS': 'Mondi Turkey Oluklu Mukavva Kağıt Ve Ambalaj',
  'MOBTL.IS': 'Mobiltel İletişim',
  'MOGAN.IS': 'Mogan Enerji Yatırım Holding',
  'MOPAS.IS': 'Mopaş Marketçilik Gıda',
  'MPARK.IS': 'Medical Park',
  'MRGYO.IS': 'Martı GYO',
  'MRSHL.IS': 'Marshall Boya',
  'MSGYO.IS': 'Mistral GYO',
  'MTRKS.IS': 'Matriks Finansal Teknolojiler',
  'MTRYO.IS': 'Metro Yatırım Ortaklığı',
  'MZHLD.IS': 'Mazhar Zorlu Holding',
  'NATEN.IS': 'Naturel Yenilenebilir Enerji',
  'NETAS.IS': 'Netaş Telekomünikasyon',
  'NETCD.IS': 'Netcad Yazılım',
  'NETGL.IS': 'Net Global Endüstriyel',
  'NIBAS.IS': 'Niğbaş Niğde Beton',
  'NTGAZ.IS': 'Naturelgaz',
  'NTHOL.IS': 'Net Holding',
  'NUGYO.IS': 'Nurol GYO',
  'NUHCM.IS': 'Nuh Çimento',
  'OBAMS.IS': 'Oba Makarnacılık',
  'OBASE.IS': 'Obase Bilgisayar',
  'ODAS.IS': 'Odaş Elektrik',
  'ODINE.IS': 'Odine Solutions Teknoloji',
  'OFSYM.IS': 'Ofis Yem Gıda',
  'ONCSM.IS': 'Oncosem Onkolojik Sistemler',
  'ONRYT.IS': 'Onur Yüksek Teknoloji',
  'ORCAY.IS': 'Orçay Ortaköy Çay',
  'ORGE.IS': 'Orge Enerji Elektrik',
  'ORMA.IS': 'Orma Orman Mahsulleri',
  'ORZAX.IS': 'Orzaks İlaç',
  'OSMEN.IS': 'Osmanlı Yatırım Menkul Değerler',
  'OSTIM.IS': 'Ostim Endüstriyel Yatırımlar Ve İşletme',
  'OTKAR.IS': 'Otokar Otobüs',
  'OTTO.IS': 'Otto Holding',
  'OYAKC.IS': 'Oyak Çimento',
  'OYAYO.IS': 'Oyak Yatırım Ortaklığı',
  'OYLUM.IS': 'Oylum Sınai Yatırımlar',
  'OYYAT.IS': 'Oyak Yatırım Menkul Değerler',
  'OZATD.IS': 'Özata Denizcilik',
  'OZGYO.IS': 'Özderici GYO',
  'OZKGY.IS': 'Özak GYO',
  'OZRDN.IS': 'Özerden Ambalaj',
  'OZSUB.IS': 'Özsu Balık',
  'OZYSR.IS': 'Özyaşar Tel Ve Galvanizleme',
  'PAGYO.IS': 'Panora GYO',
  'PAHOL.IS': 'Pasifik Holding',
  'PAMEL.IS': 'Pamel Yenilenebilir Elektrik',
  'PAPIL.IS': 'Papilon Savunma Teknoloji',
  'PARSN.IS': 'Parsan',
  'PASEU.IS': 'Pasifik Eurasia Lojistik',
  'PATEK.IS': 'Pasifik Teknoloji',
  'PCILT.IS': 'PC İletişim Ve Medya',
  'PEKGY.IS': 'Peker GYO',
  'PENGD.IS': 'Penguen Gıda',
  'PENTA.IS': 'Penta Teknoloji',
  'PETKM.IS': 'Petkim',
  'PETUN.IS': 'Pınar Et ve Un',
  'PGSUS.IS': 'Pegasus Hava Yolları',
  'PINSU.IS': 'Pınar Su Ve İçecek',
  'PKART.IS': 'Plastikkart',
  'PKENT.IS': 'Petrokent Turizm',
  'PLTUR.IS': 'Platform Turizm Taşımacılık Gıda İnşaat Temizlik',
  'PNLSN.IS': 'Panelsan Çatı Cephe Sistemleri',
  'PNSUT.IS': 'Pınar Süt',
  'POLHO.IS': 'Polisan Holding',
  'POLTK.IS': 'Politeknik Metal',
  'PRDGS.IS': 'Pardus Girişim',
  'PRKAB.IS': 'Türk Prysmian Kablo Ve Sistemleri',
  'PRKME.IS': 'Park Elektrik',
  'PRZMA.IS': 'Prizma Pres Matbaacılık Yayıncılık',
  'PSDTC.IS': 'Pergamon Dış Ticaret',
  'PSGYO.IS': 'Pasifik GYO',
  'QNBFK.IS': 'QNB Finansal Kiralama',
  'QNBTR.IS': 'QNB Bank',
  'QUAGR.IS': 'Qua Granıte Hayal Yapı Ve Ürünleri',
  'QUICK.IS': 'Quick Sigorta',
  'RALYH.IS': 'Ral Yatırım Holding',
  'RAYSG.IS': 'Ray Sigorta',
  'REEDR.IS': 'Reeder Teknoloji',
  'RGYAS.IS': 'Rönesans Gayrimenkul',
  'RNPOL.IS': 'Rainbow Polikarbonat',
  'RODRG.IS': 'Rodrigo Tekstil',
  'RTALB.IS': 'RTA Laboratuvarları',
  'RUBNS.IS': 'Rubenis Tekstil',
  'RUZYE.IS': 'Ruzy Madencilik Ve Enerji',
  'RYGYO.IS': 'Reysaş GYO',
  'RYSAS.IS': 'Reysaş Taşımacılık',
  'SAFKR.IS': 'Safkar EGE Soğutmacılık Klima Soğuk Hava Tesisleri',
  'SAHOL.IS': 'Sabancı Holding',
  'SAMAT.IS': 'Saray Matbaacılık Kağıtçılık Kırtasiyecilik',
  'SANEL.IS': 'Sanel Mühendislik',
  'SANFM.IS': 'Sanifoam Sünger',
  'SANKO.IS': 'Sanko Pazarlama',
  'SARAE.IS': 'Şa-Ra Enerji',
  'SARKY.IS': 'Sarkuysan',
  'SASA.IS': 'SASA Polyester',
  'SAYAS.IS': 'Say Reklamcılık',
  'SDTTR.IS': 'SDT Uzay Ve Savunma Teknolojileri',
  'SEGMN.IS': 'Seğmen Kardeşler Gıda Üretim Ve Ambalaj',
  'SEGYO.IS': 'Şeker GYO',
  'SEKFK.IS': 'Şeker Finansal Kiralama',
  'SEKUR.IS': 'Sekuro Plastik',
  'SELEC.IS': 'Selçuk Ecza Deposu',
  'SELVA.IS': 'Selva Gıda',
  'SERNT.IS': 'Seranit Granit Seramik',
  'SEYKM.IS': 'Seyitler Kimya',
  'SILVR.IS': 'Silverline Endüstri',
  'SISE.IS': 'Şişe Cam',
  'SKBNK.IS': 'Şekerbank',
  'SKTAS.IS': 'Söktaş Tekstil',
  'SKYLP.IS': 'Skyalp Finansal Teknolojiler Ve Danışmanlık',
  'SKYMD.IS': 'Şeker Yatırım Menkul Değerler',
  'SMART.IS': 'Smart Güneş Enerji',
  'SMRTG.IS': 'Smart Güneş Enerjisi',
  'SMRVA.IS': 'Sümer Varlık Yönetim',
  'SNGYO.IS': 'Sinpaş GYO',
  'SNICA.IS': 'Sanica Isı',
  'SNPAM.IS': 'Sönmez Pamuklu',
  'SODSN.IS': 'Sodaş Sodyum',
  'SOHOE.IS': 'Soho Giyim ve Enerji',
  'SOKE.IS': 'Söke Değirmencilik',
  'SOKM.IS': 'Şok Marketler',
  'SONME.IS': 'Sönmez Filament Sentetik İplik Ve Elyaf',
  'SRVGY.IS': 'Servet GYO',
  'SSAAT.IS': 'Saat ve Saat',
  'SUMAS.IS': 'Sumaş Suni Tahta Ve Mobilya',
  'SUNTK.IS': 'Sun Tekstil',
  'SURGY.IS': 'Sur Tatil Evleri GYO',
  'SUWEN.IS': 'Suwen Tekstil',
  'SVGYO.IS': 'Savur GYO',
  'TABGD.IS': 'Tab Gıda',
  'TARKM.IS': 'Tarkim Bitki Koruma',
  'TATEN.IS': 'Tatlıpınar Enerji',
  'TATGD.IS': 'Tat Gıda',
  'TAVHL.IS': 'TAV Havalimanları',
  'TBORG.IS': 'Türk Tuborg Bira Ve Malt',
  'TCELL.IS': 'Turkcell',
  'TCKRC.IS': 'Kıraç Galvaniz Telekominikasyon Metal Makine İnşaat Elektrik',
  'TDGYO.IS': 'Trend GYO',
  'TEHOL.IS': 'Tera Yatırım Teknoloji Holding',
  'TEKTU.IS': 'Tek-Art Turizm',
  'TERA.IS': 'Tera Yatırım Menkul Değerler',
  'TEZOL.IS': 'Europap Tezol Kağıt',
  'TGSAS.IS': 'TGS',
  'THYAO.IS': 'Türk Hava Yolları',
  'TKFEN.IS': 'Tekfen Holding',
  'TKNKA.IS': 'Teknika Plast',
  'TKNSA.IS': 'Teknosa',
  'TLMAN.IS': 'Trabzon Liman İşletmeciliği',
  'TMPOL.IS': 'Temapol Polimer Plastik',
  'TMSN.IS': 'Tümosan Motor',
  'TNZTP.IS': 'Tapdi Oksijen Özel Sağlık Ve Eğitim',
  'TOASO.IS': 'Tofaş Oto Fab.',
  'TRALT.IS': 'Türk Altın İşletmeleri',
  'TRCAS.IS': 'Turcas Holding',
  'TRENJ.IS': 'TR Doğal Enerji Kaynakları Araştırma',
  'TRGYO.IS': 'Torunlar GYO',
  'TRHOL.IS': 'Tera Finansal Yatırımlar Holding',
  'TRILC.IS': 'Turk İlaç ve Serum',
  'TRMET.IS': 'TR Anadolu Metal Madencilik İşletmeleri',
  'TSGYO.IS': 'TSKB GYO',
  'TSKB.IS': 'T.S.K.B.',
  'TSPOR.IS': 'Trabzonspor Sportif Yatırım Ve Futbol İşletmeciliği',
  'TTKOM.IS': 'Türk Telekom',
  'TTRAK.IS': 'Türk Traktör',
  'TUCLK.IS': 'Tuğçelik Alüminyum Ve Metal Mamülleri',
  'TUKAS.IS': 'Tukaş Gıda',
  'TUPRS.IS': 'Tüpraş',
  'TUREX.IS': 'TUREKS Turizm Taşımacılık',
  'TURGG.IS': 'Türker Proje Gayrimenkul Ve Yatırım Geliştirme',
  'TURSG.IS': 'Türkiye Sigorta',
  'UCAYM.IS': 'Üçay Mühendislik Enerji Ve İklimlendirme Teknolojileri',
  'UFUK.IS': 'Ufuk Yatırım',
  'ULAS.IS': 'Ulaşlar Turizm',
  'ULKER.IS': 'Ülker Bisküvi',
  'ULUFA.IS': 'Ulusal Faktoring',
  'ULUSE.IS': 'Ulusoy Elektrik',
  'ULUUN.IS': 'Ulusoy Un',
  'UNLU.IS': 'Ünlü Yatırım Holding',
  'USAK.IS': 'Uşak Seramik',
  'USHOL.IS': 'Us Yatırım Holding',
  'VAKBN.IS': 'Vakıfbank',
  'VAKFA.IS': 'Vakıf Faktoring',
  'VAKFN.IS': 'Vakıf Finansal Kiralama',
  'VAKKO.IS': 'Vakko Tekstil',
  'VANGD.IS': 'Van Et Entegre',
  'VBTYZ.IS': 'VBT Yazılım',
  'VERTU.IS': 'Verusaturk Girişim Sermayesi Yatırım Ortaklığı',
  'VERUS.IS': 'Verusa Holding',
  'VESBE.IS': 'Vestel Beyaz Eşya',
  'VESTL.IS': 'Vestel Elektronik',
  'VEYAS.IS': 'Türker Vangölü Enerji',
  'VKFYO.IS': 'Vakıf Menkul Kıymet Yatırım Ortaklığı',
  'VKGYO.IS': 'Vakıf GYO',
  'VKING.IS': 'Viking Kağıt',
  'VRGYO.IS': 'Vera Konsept GYO',
  'VSNMD.IS': 'Vişne Madencilik',
  'YAPRK.IS': 'Yaprak Süt Ve Besi Çiftlikleri',
  'YATAS.IS': 'Yataş Yatak',
  'YAYLA.IS': 'Yayla Agro Gıda',
  'YBTAS.IS': 'Yibitaş Yozgat',
  'YEOTK.IS': 'Yeo Teknoloji Enerji Ve Endüstri',
  'YESIL.IS': 'Yeşil Yatırım Holding',
  'YGGYO.IS': 'Yeni Gimat GYO',
  'YIGIT.IS': 'Yiğit Akü Malzemeleri Nakliyat Turizm',
  'YKBNK.IS': 'Yapı Kredi Bankası',
  'YKSLN.IS': 'Yükselen Çelik',
  'YONGA.IS': 'Yonga Mobilya',
  'YUNSA.IS': 'Yünsa Yünlü Sanayi',
  'YYAPI.IS': 'Yeşil Yapı Endüstrisi',
  'YYLGD.IS': 'Yayla Agro Gıda',
  'ZEDUR.IS': 'Zedur Enerji',
  'ZERGY.IS': 'Zeray GYO',
  'ZGYO.IS': 'Z GYO',
  'ZOREN.IS': 'Zorlu Enerji',
  'ZRGYO.IS': 'Ziraat GYO',
};

/// Artık işlem görmeyen ya da hiç var olmamış eski kodlar (2026-10-10
/// öncesi listede vardı). Seçicide ve aramada GÖSTERİLMEZ — fiyatı
/// gelmeyen hisse seçtirmek hatadır. Yalnız geçmiş ekstre/CSV'deki kodu
/// tanımak için tutulur (`bistKoduMu`): 2024 tarihli bir ekstrede KOZAL
/// satırı hâlâ hisse satırıdır.
const bistEskiSemboller = <String, String>{
  'AHGZT.IS': 'Ahlatcı Doğalgaz',
  'BIOTK.IS': 'Biotek Tarım',
  'CARFA.IS': 'CarrefourSA',
  'ENKA.IS': 'ENKA İnşaat',
  'IPEKE.IS': 'İpek Doğal Enerji',
  'ISATR.IS': 'İş Bankası (A)',
  'ITTFH.IS': 'İttifak Holding',
  'KERVT.IS': 'Kerevitaş Gıda',
  'KOZAA.IS': 'Koza Madencilik',
  'KOZAL.IS': 'Koza Altın',
  'METUR.IS': 'Metemtur Otelcilik',
  'MIPAZ.IS': 'Milpa Ticari',
  'MRDIN.IS': 'Mardin Çimento',
  'QNBFB.IS': 'QNB Finansbank',
  'SODA.IS': 'Soda Sanayii',
  'TKURU.IS': 'Taze Kuru Gıda',
  'UNYEC.IS': 'Ünye Çimento',
  'UTPYA.IS': 'Utopya Turizm',
  'YGYO.IS': 'Yeşil GYO',
  'YKGYO.IS': 'Yapı Kredi Koray GYO',
};

/// [kod] (ör. `THYAO` ya da `THYAO.IS`) bilinen bir BIST hisse kodu mu —
/// bugünkü ya da eski. İçe aktarma tanıması bunu kullanır; seçici
/// [bist100StocksMap]'i.
bool bistKoduMu(String kod) {
  final k = kod.toUpperCase().endsWith('.IS')
      ? kod.toUpperCase()
      : '${kod.toUpperCase()}.IS';
  return bist100StocksMap.containsKey(k) || bistEskiSemboller.containsKey(k);
}
