-- 0139 — BIST hisse kataloğu sunucuda, her gün borsadan (2026-10-10)
--
-- ## Neden
-- yasin (2026-10-10): "Eksik varlık olmasını istemiyorum, borsada işlem
-- gören tüm hisseler olmalı." Hisse listesi uygulamaya gömülüydü; elle
-- tutulduğu için eskidi (BIST 100'ün 24'ü, KUTPO gibi yüzlerce hisse yoktu)
-- ve her halka arz yeni bir sürüm bekliyordu. Liste artık burada:
-- `bist-hisse-katalog` fonksiyonu her sabah borsadan (TradingView evreni +
-- KAP unvanları) tazeler, istemci okur ve cihazda saklar. Sunucuya
-- ulaşamayan istemci gömülü listeye (`lib/models/bist_hisseleri.dart`) düşer.
--
-- ## Kural
-- * Yeni kod eklenir; var olan satırın ADI ezilmez (seed'deki elle
--   düzeltilmiş adlar korunur).
-- * Görülmeyen kod silinmez, `aktif = false` olur (kod değişti / borsadan
--   çıktı). Fiyat bu tablodan GELMEZ; fiyat kaynağı sözleşmesi değişmez.
--
-- ## Eski istemciler
-- Yalnız EKLER: bir tablo, bir tetikleyici, bir cron işi. Eski build
-- tabloyu hiç okumaz, gömülü listesiyle çalışmaya devam eder.
--
-- ## Dağıtım sırası
-- Bu migration (iki sunucu) → `bist-hisse-katalog` fonksiyonu → ilk tur
-- elle: `select public.trigger_bist_hisse_katalog();` → kontrol:
-- `select count(*) filter (where aktif), count(*) filter (where xu100), max(guncellendi) from public.bist_hisse;`
-- Seed fonksiyon hiç koşmasa da tabloyu doldurur (628 hisse, 2026-10-10).

-- ── 1) Tablo ────────────────────────────────────────────────────────────────
create table if not exists public.bist_hisse (
  kod          text        primary key check (kod ~ '^[A-Z0-9]{3,6}$'),
  ad           text        not null check (length(ad) between 2 and 120),
  -- BIST 100 üyesi mi (bilgi; seçici bugün kullanmıyor).
  xu100        boolean     not null default false,
  -- Borsada bugün işlem görüyor mu. Düşen satır silinmez.
  aktif        boolean     not null default true,
  ilk_goruldu  timestamptz not null default now(),
  guncellendi  timestamptz not null default now()
);

comment on table public.bist_hisse is
  'Borsada islem goren BIST hisseleri (bist-hisse-katalog, gunluk). Uygulamanin hisse secicisi ve aramasi buradan okur; gomulu listeye duser.';

-- ── 2) Seed (2026-10-10 ölçümü; gömülü listeyle birebir) ───────────────────
insert into public.bist_hisse (kod, ad, xu100) values
  ('A1CAP', 'A1 Capital Yatırım Menkul Değerler', false),
  ('A1YEN', 'A1 Yenilenebilir Enerji', false),
  ('AAGYO', 'Ağaoğlu Avrasya GYO', false),
  ('ACSEL', 'Acıselsan Acıpayam Selüloz', false),
  ('ADEL', 'Adel Kalemcilik', false),
  ('ADESE', 'Adese Gayrimenkul', false),
  ('ADGYO', 'Adra GYO', false),
  ('AEFES', 'Anadolu Efes', true),
  ('AFYON', 'Afyon Çimento', false),
  ('AGESA', 'Agesa Hayat ve Emeklilik', false),
  ('AGHOL', 'AG Anadolu Grubu Holding', true),
  ('AGROT', 'Agrotech Yüksek Teknoloji', false),
  ('AGYO', 'Atakule GYO', false),
  ('AHGAZ', 'Ahlatcı Doğal Gaz Dağıtım Enerji', true),
  ('AHSGY', 'Ahes GYO', false),
  ('AKBNK', 'Akbank', true),
  ('AKCNS', 'Akçansa Çimento', true),
  ('AKENR', 'Ak Enerji', false),
  ('AKFGY', 'Akfen GYO', false),
  ('AKFIS', 'Akfen İnşaat Turizm', false),
  ('AKFYE', 'Akfen Yenilenebilir Enerji', true),
  ('AKGRT', 'Aksigorta', false),
  ('AKHAN', 'Akhan Un Fabrikası ve Tarım Ürünleri Gıda', false),
  ('AKMGY', 'Akmerkez GYO', false),
  ('AKSA', 'Aksa Akrilik', true),
  ('AKSEN', 'Aksa Enerji', true),
  ('AKSGY', 'Akiş GYO', false),
  ('AKSUE', 'Aksu Enerji', false),
  ('AKYHO', 'Akdeniz Yatırım Holding', false),
  ('ALARK', 'Alarko Holding', true),
  ('ALBRK', 'Albaraka Türk', true),
  ('ALBTN', 'Albayrak Hazır Beton', false),
  ('ALCAR', 'Alarko Carrıer', false),
  ('ALCTL', 'Alcatel Lucent Teleteknik', false),
  ('ALFAS', 'Alfa Solar Enerji', false),
  ('ALGYO', 'Alarko GYO', false),
  ('ALKA', 'Alkim Kağıt', false),
  ('ALKIM', 'Alkim Alkali Kimya', false),
  ('ALKLC', 'Altınkılıç Gıda ve Süt', false),
  ('ALTNY', 'Altınay Savunma Teknolojileri', true),
  ('ALVES', 'Alves Kablo', false),
  ('ANELE', 'Anel Elektrik', false),
  ('ANGEN', 'Anatolia Tanı ve Biyoteknoloji Ürünleri Araştırma Geliştirme', false),
  ('ANHYT', 'Anadolu Hayat Emeklilik', true),
  ('ANSGR', 'Anadolu Sigorta', true),
  ('ARASE', 'Aras Elektrik Dağıtım', false),
  ('ARCLK', 'Arçelik', true),
  ('ARDYZ', 'ARD Bilişim Teknolojileri', false),
  ('ARENA', 'Arena Bilgisayar', false),
  ('ARFYE', 'Arf Bio Yenilenebilir Enerji', false),
  ('ARMGD', 'Armada Gıda', false),
  ('ARSAN', 'Arsan Tekstil', false),
  ('ARTMS', 'Artemis Halı', false),
  ('ARZUM', 'Arzum Elektrikli Ev Aletleri', false),
  ('ASELS', 'Aselsan', true),
  ('ASGYO', 'Asce GYO', false),
  ('ASTOR', 'Astor Enerji', true),
  ('ASUZU', 'Anadolu Isuzu', false),
  ('ATAGY', 'Ata GYO', false),
  ('ATAKP', 'Atakey Patates', false),
  ('ATATP', 'ATA Teknoloji Platformu', false),
  ('ATATR', 'Ata Turizm İşletmecilik Taşımacılık Madencilik Kuyumculuk', false),
  ('ATEKS', 'Akın Tekstil', false),
  ('ATLAS', 'Atlas Menkul Kıymetler Yatırım Ortaklığı', false),
  ('ATSYH', 'Atlantis Yatırım Holding', false),
  ('AVGYO', 'Avrasya GYO', false),
  ('AVHOL', 'Avrupa Yatırım Holding', false),
  ('AVOD', 'A.V.O.D. Gıda', false),
  ('AVPGY', 'Avrupakent GYO', false),
  ('AVTUR', 'Avrasya Petrol Turistik', false),
  ('AYCES', 'Altınyunus Çeşme', false),
  ('AYDEM', 'Aydem Yenilenebilir Enerji', false),
  ('AYEN', 'Ayen Enerji', false),
  ('AYES', 'Ayes Çelik Hasır ve Çit', false),
  ('AYGAZ', 'Aygaz', true),
  ('AZTEK', 'Aztek Teknoloji Ürünleri', false),
  ('BAGFS', 'Bagfaş Bandırma Gübre', false),
  ('BAHKM', 'Bahadır Kimya', false),
  ('BAKAB', 'Bak Ambalaj', false),
  ('BALAT', 'Balatacılar Balatacılık', false),
  ('BALSU', 'Balsu Gıda', false),
  ('BANVT', 'Banvit', false),
  ('BARMA', 'Barem Ambalaj', false),
  ('BASCM', 'Baştaş Çimento', false),
  ('BASGZ', 'Başkent Doğalgaz', false),
  ('BAYRK', 'Bayrak EBT', false),
  ('BEGYO', 'Batı EGE GYO', false),
  ('BERA', 'Bera Holding', true),
  ('BESLR', 'Besler Gıda ve Kimya', false),
  ('BESTE', 'Best Brands Grup Enerji', false),
  ('BETAE', 'Beta Enerji ve Teknoloji', false),
  ('BEYAZ', 'Beyaz Filo', false),
  ('BFREN', 'Bosch Fren Sistemleri', false),
  ('BIENY', 'Bien Yapı Ürünleri Sanayi Turizm', false),
  ('BIGCH', 'Büyük Şefler Gıda Turizm Tekstil Danışmanlık Organizasyon Eğitim', false),
  ('BIGEN', 'Birleşim Grup Enerji', false),
  ('BIGTK', 'Big Medya Teknoloji', false),
  ('BIMAS', 'BİM Mağazalar', true),
  ('BINBN', 'Bin Ulaşım ve Akıllı Şehir Teknolojileri', false),
  ('BINHO', 'Bin Holding', true),
  ('BIOEN', 'Biotrend Enerji', false),
  ('BIZIM', 'Bizim Toptan Satış', false),
  ('BJKAS', 'Beşiktaş Futbol', false),
  ('BKRGY', 'Bakırcı GYO', false),
  ('BLCYT', 'Bilici Yatırım', false),
  ('BLUME', 'Blume Metal Kimya', false),
  ('BMSCH', 'BMS Çelik Hasır', false),
  ('BMSTL', 'BMS Birleşik Metal', false),
  ('BNTAS', 'Bantaş Ambalaj', false),
  ('BOBET', 'Boğaziçi Beton', false),
  ('BORLS', 'Borlease Otomotiv', false),
  ('BORSK', 'Bor Şeker', false),
  ('BOSSA', 'Bossa Ticaret', false),
  ('BRISA', 'Brisa Bridgestone', false),
  ('BRKO', 'Birko Mensucat', false),
  ('BRKSN', 'Berkosan Yalıtım', false),
  ('BRKVY', 'Birikim Varlık Yönetim', false),
  ('BRLSM', 'Birleşim Mühendislik Isıtma Soğutma Havalandırma', false),
  ('BRMEN', 'Birlik Mensucat Ticaret ve Sanayi İşletmesi', false),
  ('BRSAN', 'Borusan Birleşik Boru Fabrikaları', true),
  ('BRYAT', 'Borusan', true),
  ('BSOKE', 'Batısöke Çimento', false),
  ('BTCIM', 'Batıçim Batı Anadolu', true),
  ('BUCIM', 'Bursa Çimento', false),
  ('BULGS', 'Bulls Girişim Sermayesi Yatırım Ortaklığı', false),
  ('BURCE', 'Burçelik', false),
  ('BURVA', 'Burçelik Vana', false),
  ('BVSAN', 'Bülbüloğlu Vinç', false),
  ('BYDNR', 'Baydöner Restoranları', false),
  ('CANTE', 'Çan2 Termik', true),
  ('CASA', 'Casa Emtia Petrol Kimyevi ve Türevleri', false),
  ('CATES', 'Çates Elektrik', false),
  ('CCOLA', 'Coca-Cola İçecek', true),
  ('CELHA', 'Çelik Halat ve Tel', false),
  ('CEMAS', 'Çemaş Döküm', false),
  ('CEMTS', 'Çemtaş Çelik', false),
  ('CEMZY', 'Cem Zeytin', false),
  ('CEOEM', 'Ceo Event Medya', false),
  ('CGCAM', 'Çağdaş Cam', false),
  ('CIMSA', 'Çimsa Çimento', true),
  ('CITAS', 'Çitlekçi Mağazacılık', false),
  ('CLEBI', 'Çelebi Havacılık', false),
  ('CMBTN', 'Çimbeton', false),
  ('CMENT', 'Çimentaş', false),
  ('CONSE', 'Consus Enerji', false),
  ('COSMO', 'Cosmos Yatırım Holding', false),
  ('CRDFA', 'Creditwest Faktoring', false),
  ('CRFSA', 'Carrefoursa Carrefour Sabancı Ticaret Merkezi', false),
  ('CUSAN', 'Çuhadaroğlu Metal', false),
  ('CVKMD', 'CVK Maden İşletmeleri', true),
  ('CWENE', 'CW Enerji', true),
  ('DAGI', 'Dagi Yatırım Holding', false),
  ('DAPGM', 'Dap Gayrimenkul Geliştirme', false),
  ('DARDL', 'Dardanel Önentaş', false),
  ('DCTTR', 'DCT Trading', false),
  ('DENGE', 'Denge Yatırım Holding', false),
  ('DERHL', 'Derlüks Yatırım Holding', false),
  ('DERIM', 'Derimod Konfeksiyon Ayakkabı Deri', false),
  ('DESA', 'Desa Deri', false),
  ('DESPC', 'Despec Bilgisayar', false),
  ('DEVA', 'Deva Holding', false),
  ('DGATE', 'Datagate Bilgisayar', false),
  ('DGGYO', 'Doğuş GYO', false),
  ('DGNMO', 'Doğan Trend Otomotiv', false),
  ('DIRIT', 'Diriteks Diriliş Tekstil', false),
  ('DITAS', 'Ditaş Doğan', false),
  ('DMRGD', 'DMR Unlu Mamuller Üretim Gıda Toptan Perakende', false),
  ('DMSAS', 'Demisaş Döküm', false),
  ('DNISI', 'Dinamik Isı Makina Yalıtım Malzemeleri', false),
  ('DOAS', 'Doğuş Otomotiv', true),
  ('DOCO', 'Do \\u0026 Co Aktıengesellschaft', false),
  ('DOFER', 'Dofer Yapı Malzemeleri', false),
  ('DOFRB', 'Dof Robotik', false),
  ('DOGUB', 'Doğusan Boru', false),
  ('DOHOL', 'Doğan Holding', true),
  ('DOKTA', 'Döktaş Dökümcülük', false),
  ('DSTKF', 'Destek Finans Faktoring', false),
  ('DUNYH', 'Dünya Holding', false),
  ('DURDO', 'Duran Doğan Basım', false),
  ('DURKN', 'Durukan Şekerleme', false),
  ('DYOBY', 'DYO Boya', false),
  ('DZGYO', 'Deniz GYO', false),
  ('EBEBK', 'Ebebek Mağazacılık', false),
  ('ECILC', 'Eczacıbaşı İlaç', true),
  ('ECOGR', 'Ecogreen Enerji Holding', false),
  ('ECZYT', 'Eczacıbaşı Yatırım', true),
  ('EDATA', 'E-data Teknoloji', false),
  ('EDIP', 'Edip Gayrimenkul', false),
  ('EFOR', 'Efor', false),
  ('EGEEN', 'Ege Endüstri', true),
  ('EGEGY', 'Egeyapı Avrupa GYO', false),
  ('EGEPO', 'Ege Profil', false),
  ('EGGUB', 'Ege Gübre', true),
  ('EGPRO', 'EGE Profil', false),
  ('EGSER', 'EGE Seramik', false),
  ('EKDMR', 'Ekinciler Demir ve Çelik', false),
  ('EKGYO', 'Emlak Konut GYO', true),
  ('EKIM', 'Ekim Turizm (Intercity)', false),
  ('EKIZ', 'Ekiz Kimya', false),
  ('EKOS', 'Ekos Teknoloji ve Elektrik', false),
  ('EKSUN', 'Eksun Gıda Tarım', false),
  ('ELITE', 'Elite Naturel Organik Gıda', false),
  ('EMKEL', 'Emek Elektrik', false),
  ('EMNIS', 'Eminiş Ambalaj', false),
  ('EMPAE', 'Empa Elektronik', false),
  ('ENDAE', 'Enda Enerji Holding', false),
  ('ENERY', 'Enerya Enerji', true),
  ('ENJSA', 'Enerjisa Enerji', true),
  ('ENKAI', 'Enka', true),
  ('ENPRA', 'Enpara Bank', false),
  ('ENSRI', 'Ensari Sınai Yatırımlar', false),
  ('ENTRA', 'Ic Enterra Yenilenebilir Enerji', true),
  ('EPLAS', 'Egeplast EGE Plastik', false),
  ('ERBOS', 'Erbosan', false),
  ('ERCB', 'Erciyas Çelik Boru', false),
  ('EREGL', 'Ereğli Demir Çelik', true),
  ('ERSU', 'Ersu Meyve ve Gıda', false),
  ('ESCAR', 'Escar Filo Kiralama', false),
  ('ESCOM', 'Escort Teknoloji', false),
  ('ESEN', 'Esenboğa Elektrik', false),
  ('ETILR', 'Etiler Gıda ve Ticari Yatırımlar', false),
  ('ETYAT', 'Euro Trend Yatırım Ortaklığı', false),
  ('EUHOL', 'Euro Yatırım Holding', false),
  ('EUKYO', 'Euro Kapital Yatırım Ortaklığı', false),
  ('EUPWR', 'Europower Enerji', false),
  ('EUREN', 'Europen Endüstri', true),
  ('EUYO', 'Euro Menkul Kıymet Yatırım Ortaklığı', false),
  ('EYGYO', 'Eyg GYO', false),
  ('FADE', 'Fade Gıda', false),
  ('FENER', 'Fenerbahçe Futbol', true),
  ('FLAP', 'Flap Kongre Toplantı Hizmetleri Otomotiv ve Turizm', false),
  ('FMIZP', 'Federal-Mogul İzmit Piston', false),
  ('FONET', 'Fonet Bilgi Teknolojileri', false),
  ('FORMT', 'Formet Metal ve Cam', false),
  ('FORTE', 'Forte Bilgi İletişim Teknolojileri ve Savunma', false),
  ('FRIGO', 'Frigo Pak Gıda', false),
  ('FRMPL', 'Formül Plastik ve Metal', false),
  ('FROTO', 'Ford Otosan', true),
  ('FZLGY', 'Fuzul GYO', false),
  ('GARAN', 'Garanti BBVA', true),
  ('GARFA', 'Garanti Faktoring', false),
  ('GATEG', 'Gate Group Teknoloji Medya ve Siber Güvenlik', false),
  ('GEDIK', 'Gedik Yatırım Menkul Değerler', false),
  ('GEDZA', 'Gediz Ambalaj', false),
  ('GENIL', 'Gen İlaç ve Sağlık Ürünleri', false),
  ('GENKM', 'Gentaş Kimya', false),
  ('GENTS', 'Gentaş Genel Metal', false),
  ('GEREL', 'Gersan Elektrik', false),
  ('GESAN', 'Girişim Elektrik Sanayi Taahhüt', false),
  ('GIPTA', 'Gıpta Ofis Kırtasiye ve Promosyon Ürünleri İmalat', false),
  ('GLBMD', 'Global Menkul Değerler', false),
  ('GLCVY', 'Gelecek Varlık Yönetimi', false),
  ('GLRMK', 'Gülermak Ağır Sanayi İnşaat ve Taahhüt', true),
  ('GLRYH', 'Güler Yatırım Holding', false),
  ('GLYHO', 'Global Yatırım Holding', true),
  ('GMTAS', 'Gimat Mağazacılık', false),
  ('GOKNR', 'Göknur Gıda Maddeleri Enerji İmalat', false),
  ('GOLDA', 'Golda Gıda', false),
  ('GOLTS', 'Göltaş Çimento', false),
  ('GOODY', 'Goodyear Lastikleri', false),
  ('GOZDE', 'Gözde Girişim Sermayesi Yatırım Ortaklığı', false),
  ('GRNYO', 'Garanti Yatırım Ortaklığı', false),
  ('GRSEL', 'Gür-Sel Turizm Taşımacılık ve Servis', true),
  ('GRTHO', 'Graınturk Holding', false),
  ('GSDDE', 'GSD Denizcilik Gayrimenkul', false),
  ('GSDHO', 'GSD Holding', false),
  ('GSRAY', 'Galatasaray Sportif Sınai ve Ticari Yatırımlar', false),
  ('GUBRF', 'Gübre Fabrikaları', true),
  ('GUNDG', 'Gündoğdu Gıda Süt Ürünleri', false),
  ('GWIND', 'Galata Wind Enerji', true),
  ('GZNMI', 'Gezinomi Seyahat Turizm', false),
  ('HALKB', 'Halkbank', true),
  ('HATEK', 'Hateks Hatay Tekstil İşletmeleri', false),
  ('HATSN', 'Hat-San Gemi İnşaa Bakım Onarım Deniz Nakliyat', false),
  ('HDFGS', 'Hedef Girişim Sermayesi Yatırım Ortaklığı', false),
  ('HEDEF', 'Hedef Holding', false),
  ('HEKTS', 'Hektaş Ticaret', true),
  ('HKTM', 'Hidropar Hareket Kontrol Teknolojileri Merkezi', false),
  ('HLGYO', 'Halk GYO', false),
  ('HOROZ', 'Horoz Lojistik Kargo', false),
  ('HRKET', 'Hareket Proje Taşımacılığı ve Yük Mühendisliği', false),
  ('HTTBT', 'Hitit Bilgisayar', false),
  ('HUBVC', 'Hub Girişim Sermayesi Yatırım Ortaklığı', false),
  ('HUNER', 'Hun Yenilenebilir Enerji', false),
  ('HURGZ', 'Hürriyet Gazetecilik', false),
  ('ICBCT', 'ICBC Turkey Bank', false),
  ('ICUGS', 'ICU Girişim Sermayesi Yatırım Ortaklığı', false),
  ('IDGYO', 'İdealist GYO', false),
  ('IEYHO', 'Işıklar Enerji ve Yapı Holding', false),
  ('IHAAS', 'İhlas Haber Ajansı', false),
  ('IHEVA', 'İhlas Ev Aletleri İmalat', false),
  ('IHGZT', 'İhlas Gazetecilik', false),
  ('IHLAS', 'İhlas Holding', false),
  ('IHLGM', 'İhlas Gayrimenkul Proje Geliştirme', false),
  ('IHYAY', 'İhlas Yayın Holding', false),
  ('IMASM', 'İmaş Makina', false),
  ('INDES', 'İndeks Bilgisayar', false),
  ('INFO', 'İnfo Yatırım Menkul Değerler', false),
  ('INGRM', 'Ingram Micro Bilişim Sistemleri', false),
  ('INTEK', 'İnnosa Teknoloji', false),
  ('INTEM', 'İntema İnşaat', false),
  ('INTET', 'İntetra Teknoloji', false),
  ('INVEO', 'Inveo Yatırım Holding', false),
  ('INVES', 'Investco Holding', false),
  ('ISBIR', 'İşbir Holding', false),
  ('ISBTR', 'İş Bankası (B)', false),
  ('ISCTR', 'İş Bankası (C)', true),
  ('ISDMR', 'İskenderun Demir Çelik', true),
  ('ISFIN', 'İş Finansal Kiralama', false),
  ('ISGSY', 'İş Girişim Sermayesi Yatırım Ortaklığı', false),
  ('ISGYO', 'İş GYO', false),
  ('ISKPL', 'Işık Plastik', false),
  ('ISMEN', 'İş Yatırım Menkul Değerler', true),
  ('ISSEN', 'İşbir Sentetik Dokuma', false),
  ('ISVEA', 'İsvea Seramik', false),
  ('ISYAT', 'İş Yatırım Ortaklığı', false),
  ('IZENR', 'İzdemir Enerji Elektrik', false),
  ('IZFAS', 'İzmir Fırça', false),
  ('IZINV', 'İz Yatırım Holding', false),
  ('IZMDC', 'İzmir Demir Çelik', false),
  ('JANTS', 'Jantsa Jant Sanayi', false),
  ('KAPLM', 'Kaplamin Ambalaj', false),
  ('KARCL', 'Kardemir Çelik', false),
  ('KAREL', 'Karel Elektronik', false),
  ('KARSN', 'Karsan Otomotiv', true),
  ('KARTN', 'Kartonsan Karton', false),
  ('KATMR', 'Katmerciler Ekipman', true),
  ('KAYSE', 'Kayseri Şeker Fabrikası', false),
  ('KBORU', 'Kuzey Boru', false),
  ('KCAER', 'Kocaer Çelik', true),
  ('KCHOL', 'Koç Holding', true),
  ('KENT', 'Kent Gıda Maddeleri', false),
  ('KERVN', 'Kervansaray Yatırım Holding', false),
  ('KFEIN', 'Kafein Yazılım', false),
  ('KGYO', 'Koray GYO', false),
  ('KIMMR', 'Kim Mağazacılık', false),
  ('KLGYO', 'Kiler GYO', false),
  ('KLKIM', 'Kalekim Kimyevi Maddeler', false),
  ('KLMSN', 'Klimasan Klima', false),
  ('KLNMA', 'Kalkınma ve Yatırım Bankası', false),
  ('KLRHO', 'Kiler Holding', false),
  ('KLSER', 'Kaleseramik Çanakkale Kalebodur Seramik', false),
  ('KLSYN', 'Koleksiyon Mobilya', false),
  ('KLYPV', 'Kalyon Güneş Teknolojileri', false),
  ('KMPUR', 'Kimteks Poliüretan', false),
  ('KNFRT', 'Konfrut Gıda', false),
  ('KOCMT', 'Koç Metalurji', false),
  ('KONKA', 'Konya Kağıt', false),
  ('KONTR', 'Kontrolmatik Teknoloji', false),
  ('KONYA', 'Konya Çimento', false),
  ('KOPOL', 'Koza Polyester', false),
  ('KORDS', 'Kordsa Teknik', true),
  ('KOTON', 'Koton Mağazacılık Tekstil', false),
  ('KPEKS', 'Kapeks Kimya', false),
  ('KRDMA', 'Kardemir Karabük Demir Çelik', false),
  ('KRDMB', 'Kardemir Karabük Demir Çelik', false),
  ('KRDMD', 'Kardemir (D)', true),
  ('KRGYO', 'Körfez GYO', false),
  ('KRONT', 'Kron Teknoloji', false),
  ('KRPLS', 'Koroplast Temizlik Ambalaj Ürünleri', false),
  ('KRSTL', 'Kristal Kola', false),
  ('KRTEK', 'Karsu Tekstil', false),
  ('KRVGD', 'Kervan Gıda', false),
  ('KSTUR', 'Kuştur Kuşadası Turizm Endüstrisi', false),
  ('KTLEV', 'Katılımevim Tasarruf Finansman', false),
  ('KTSKR', 'Kütahya Şeker', false),
  ('KUTPO', 'Kütahya Porselen', false),
  ('KUVVA', 'Kuvva Gıda', false),
  ('KUYAS', 'Kuyaş', false),
  ('KZBGY', 'Kızılbük GYO', false),
  ('KZGYO', 'Kuzugrup GYO', false),
  ('LIDER', 'LDR Turizm', false),
  ('LIDFA', 'Lider Faktoring', false),
  ('LILAK', 'Lila Kağıt', false),
  ('LINK', 'Link Bilgisayar', false),
  ('LKMNH', 'Lokman Hekim Sağlık', false),
  ('LMKDC', 'Limak Doğu Anadolu Çimento', true),
  ('LOGO', 'Logo Yazılım', false),
  ('LRSHO', 'Loras Holding', false),
  ('LUKSK', 'Lüks Kadife', false),
  ('LXGYO', 'Luxera GYO', false),
  ('LYDHO', 'Lydia Holding', false),
  ('LYDYE', 'Lydia Yeşil Enerji Kaynakları', false),
  ('MAALT', 'Marmaris Altınyunus', false),
  ('MACKO', 'Mackolik İnternet', false),
  ('MAGEN', 'Margün Enerji', false),
  ('MAKIM', 'Makim Makina Teknolojileri', false),
  ('MAKTK', 'Makina Takım Endüstrisi', false),
  ('MANAS', 'Manas Enerji Yönetimi', false),
  ('MARBL', 'Tureks Turunç Madencilik', false),
  ('MARMR', 'Marmara Holding', false),
  ('MARTI', 'Martı Otel İşletmeleri', false),
  ('MASFN', 'Masfen Enerji', false),
  ('MAVI', 'Mavi Giyim', true),
  ('MCARD', 'Metropal Kurumsal Hizmetler', false),
  ('MEDTR', 'Meditera Tıbbi Malzeme', false),
  ('MEGAP', 'Mega Polietilen Köpük', false),
  ('MEGMT', 'Mega Metal', false),
  ('MEKAG', 'Meka Global Makine İmalat', false),
  ('MEPET', 'Mepet Metro Petrol', false),
  ('MERCN', 'Mercan Kimya', false),
  ('MERIT', 'Merit Turizm Yatırım ve İşletme', false),
  ('MERKO', 'Merko Gıda', false),
  ('METEN', 'Metgün Enerji', false),
  ('METRO', 'Metro Holding', false),
  ('MEYSU', 'Meysu Gıda', false),
  ('MGROS', 'Migros Ticaret', true),
  ('MHRGY', 'MHR GYO', false),
  ('MIATK', 'Mia Teknoloji', false),
  ('MMCAS', 'MMC Sanayi ve Ticari Yatırımlar', false),
  ('MNDRS', 'Menderes Tekstil', false),
  ('MNDTR', 'Mondi Turkey Oluklu Mukavva Kağıt ve Ambalaj', false),
  ('MOBTL', 'Mobiltel İletişim', false),
  ('MOGAN', 'Mogan Enerji Yatırım Holding', false),
  ('MOPAS', 'Mopaş Marketçilik Gıda', false),
  ('MPARK', 'Medical Park', true),
  ('MRGYO', 'Martı GYO', false),
  ('MRSHL', 'Marshall Boya', false),
  ('MSGYO', 'Mistral GYO', false),
  ('MTRKS', 'Matriks Finansal Teknolojiler', false),
  ('MTRYO', 'Metro Yatırım Ortaklığı', false),
  ('MZHLD', 'Mazhar Zorlu Holding', false),
  ('NATEN', 'Naturel Yenilenebilir Enerji', false),
  ('NETAS', 'Netaş Telekomünikasyon', false),
  ('NETCD', 'Netcad Yazılım', false),
  ('NETGL', 'Net Global Endüstriyel', false),
  ('NIBAS', 'Niğbaş Niğde Beton', false),
  ('NTGAZ', 'Naturelgaz', false),
  ('NTHOL', 'Net Holding', false),
  ('NUGYO', 'Nurol GYO', false),
  ('NUHCM', 'Nuh Çimento', false),
  ('OBAMS', 'Oba Makarnacılık', true),
  ('OBASE', 'Obase Bilgisayar', false),
  ('ODAS', 'Odaş Elektrik', true),
  ('ODINE', 'Odine Solutions Teknoloji', false),
  ('OFSYM', 'Ofis Yem Gıda', false),
  ('ONCSM', 'Oncosem Onkolojik Sistemler', false),
  ('ONRYT', 'Onur Yüksek Teknoloji', false),
  ('ORCAY', 'Orçay Ortaköy Çay', false),
  ('ORGE', 'Orge Enerji Elektrik', false),
  ('ORMA', 'Orma Orman Mahsulleri', false),
  ('ORZAX', 'Orzaks İlaç', false),
  ('OSMEN', 'Osmanlı Yatırım Menkul Değerler', false),
  ('OSTIM', 'Ostim Endüstriyel Yatırımlar ve İşletme', false),
  ('OTKAR', 'Otokar Otobüs', true),
  ('OTTO', 'Otto Holding', false),
  ('OYAKC', 'Oyak Çimento', true),
  ('OYAYO', 'Oyak Yatırım Ortaklığı', false),
  ('OYLUM', 'Oylum Sınai Yatırımlar', false),
  ('OYYAT', 'Oyak Yatırım Menkul Değerler', false),
  ('OZATD', 'Özata Denizcilik', false),
  ('OZGYO', 'Özderici GYO', false),
  ('OZKGY', 'Özak GYO', false),
  ('OZRDN', 'Özerden Ambalaj', false),
  ('OZSUB', 'Özsu Balık', false),
  ('OZYSR', 'Özyaşar Tel ve Galvanizleme', false),
  ('PAGYO', 'Panora GYO', false),
  ('PAHOL', 'Pasifik Holding', true),
  ('PAMEL', 'Pamel Yenilenebilir Elektrik', false),
  ('PAPIL', 'Papilon Savunma Teknoloji', false),
  ('PARSN', 'Parsan', false),
  ('PASEU', 'Pasifik Eurasia Lojistik', false),
  ('PATEK', 'Pasifik Teknoloji', false),
  ('PCILT', 'PC İletişim ve Medya', false),
  ('PEKGY', 'Peker GYO', false),
  ('PENGD', 'Penguen Gıda', false),
  ('PENTA', 'Penta Teknoloji', false),
  ('PETKM', 'Petkim', true),
  ('PETUN', 'Pınar Et ve Un', false),
  ('PGSUS', 'Pegasus Hava Yolları', true),
  ('PINSU', 'Pınar Su ve İçecek', false),
  ('PKART', 'Plastikkart', false),
  ('PKENT', 'Petrokent Turizm', false),
  ('PLTUR', 'Platform Turizm Taşımacılık Gıda İnşaat Temizlik', false),
  ('PNLSN', 'Panelsan Çatı Cephe Sistemleri', false),
  ('PNSUT', 'Pınar Süt', false),
  ('POLHO', 'Polisan Holding', false),
  ('POLTK', 'Politeknik Metal', false),
  ('PRDGS', 'Pardus Girişim', false),
  ('PRKAB', 'Türk Prysmian Kablo ve Sistemleri', false),
  ('PRKME', 'Park Elektrik', false),
  ('PRZMA', 'Prizma Pres Matbaacılık Yayıncılık', false),
  ('PSDTC', 'Pergamon Dış Ticaret', false),
  ('PSGYO', 'Pasifik GYO', false),
  ('QNBFK', 'QNB Finansal Kiralama', false),
  ('QNBTR', 'QNB Bank', false),
  ('QUAGR', 'Qua Granıte Hayal Yapı ve Ürünleri', false),
  ('QUICK', 'Quick Sigorta', false),
  ('RALYH', 'Ral Yatırım Holding', false),
  ('RAYSG', 'Ray Sigorta', false),
  ('REEDR', 'Reeder Teknoloji', false),
  ('RGYAS', 'Rönesans Gayrimenkul', true),
  ('RNPOL', 'Rainbow Polikarbonat', false),
  ('RODRG', 'Rodrigo Tekstil', false),
  ('RTALB', 'RTA Laboratuvarları', false),
  ('RUBNS', 'Rubenis Tekstil', false),
  ('RUZYE', 'Ruzy Madencilik ve Enerji', false),
  ('RYGYO', 'Reysaş GYO', false),
  ('RYSAS', 'Reysaş Taşımacılık', true),
  ('SAFKR', 'Safkar Ege Soğutmacılık Klima Soğuk Hava Tesisleri', false),
  ('SAHOL', 'Sabancı Holding', true),
  ('SAMAT', 'Saray Matbaacılık Kağıtçılık Kırtasiyecilik', false),
  ('SANEL', 'Sanel Mühendislik', false),
  ('SANFM', 'Sanifoam Sünger', false),
  ('SANKO', 'Sanko Pazarlama', false),
  ('SARAE', 'Şa-Ra Enerji', false),
  ('SARKY', 'Sarkuysan', false),
  ('SASA', 'SASA Polyester', true),
  ('SAYAS', 'Say Reklamcılık', false),
  ('SDTTR', 'SDT Uzay ve Savunma Teknolojileri', false),
  ('SEGMN', 'Seğmen Kardeşler Gıda Üretim ve Ambalaj', false),
  ('SEGYO', 'Şeker GYO', false),
  ('SEKFK', 'Şeker Finansal Kiralama', false),
  ('SEKUR', 'Sekuro Plastik', false),
  ('SELEC', 'Selçuk Ecza Deposu', false),
  ('SELVA', 'Selva Gıda', false),
  ('SERNT', 'Seranit Granit Seramik', false),
  ('SEYKM', 'Seyitler Kimya', false),
  ('SILVR', 'Silverline Endüstri', false),
  ('SISE', 'Şişe Cam', true),
  ('SKBNK', 'Şekerbank', false),
  ('SKTAS', 'Söktaş Tekstil', false),
  ('SKYLP', 'Skyalp Finansal Teknolojiler ve Danışmanlık', false),
  ('SKYMD', 'Şeker Yatırım Menkul Değerler', false),
  ('SMART', 'Smart Güneş Enerji', false),
  ('SMRTG', 'Smart Güneş Enerjisi', false),
  ('SMRVA', 'Sümer Varlık Yönetim', false),
  ('SNGYO', 'Sinpaş GYO', true),
  ('SNICA', 'Sanica Isı', false),
  ('SNPAM', 'Sönmez Pamuklu', false),
  ('SODSN', 'Sodaş Sodyum', false),
  ('SOHOE', 'Soho Giyim ve Enerji', false),
  ('SOKE', 'Söke Değirmencilik', false),
  ('SOKM', 'Şok Marketler', true),
  ('SONME', 'Sönmez Filament Sentetik İplik ve Elyaf', false),
  ('SRVGY', 'Servet GYO', false),
  ('SSAAT', 'Saat ve Saat', false),
  ('SUMAS', 'Sumaş Suni Tahta ve Mobilya', false),
  ('SUNTK', 'Sun Tekstil', false),
  ('SURGY', 'Sur Tatil Evleri GYO', false),
  ('SUWEN', 'Suwen Tekstil', false),
  ('SVGYO', 'Savur GYO', false),
  ('TABGD', 'Tab Gıda', true),
  ('TARKM', 'Tarkim Bitki Koruma', false),
  ('TATEN', 'Tatlıpınar Enerji', false),
  ('TATGD', 'Tat Gıda', false),
  ('TAVHL', 'TAV Havalimanları', true),
  ('TBORG', 'Türk Tuborg Bira ve Malt', false),
  ('TCELL', 'Turkcell', true),
  ('TCKRC', 'Kıraç Galvaniz Telekominikasyon Metal Makine İnşaat Elektrik', true),
  ('TDGYO', 'Trend GYO', false),
  ('TEHOL', 'Tera Yatırım Teknoloji Holding', false),
  ('TEKTU', 'Tek-Art Turizm', false),
  ('TERA', 'Tera Yatırım Menkul Değerler', false),
  ('TEZOL', 'Europap Tezol Kağıt', false),
  ('TGSAS', 'TGS', false),
  ('THYAO', 'Türk Hava Yolları', true),
  ('TKFEN', 'Tekfen Holding', true),
  ('TKNKA', 'Teknika Plast', false),
  ('TKNSA', 'Teknosa', false),
  ('TLMAN', 'Trabzon Liman İşletmeciliği', false),
  ('TMPOL', 'Temapol Polimer Plastik', false),
  ('TMSN', 'Tümosan Motor', false),
  ('TNZTP', 'Tapdi Oksijen Özel Sağlık ve Eğitim', false),
  ('TOASO', 'Tofaş Oto Fab.', true),
  ('TRALT', 'Türk Altın İşletmeleri', true),
  ('TRCAS', 'Turcas Holding', false),
  ('TRENJ', 'TR Doğal Enerji Kaynakları Araştırma', true),
  ('TRGYO', 'Torunlar GYO', true),
  ('TRHOL', 'Tera Finansal Yatırımlar Holding', false),
  ('TRILC', 'Turk İlaç ve Serum', false),
  ('TRMET', 'TR Anadolu Metal Madencilik İşletmeleri', true),
  ('TSGYO', 'TSKB GYO', false),
  ('TSKB', 'T.S.K.B.', true),
  ('TSPOR', 'Trabzonspor Sportif Yatırım ve Futbol İşletmeciliği', false),
  ('TTKOM', 'Türk Telekom', true),
  ('TTRAK', 'Türk Traktör', true),
  ('TUCLK', 'Tuğçelik Alüminyum ve Metal Mamülleri', false),
  ('TUKAS', 'Tukaş Gıda', true),
  ('TUPRS', 'Tüpraş', true),
  ('TUREX', 'Tureks Turizm Taşımacılık', false),
  ('TURGG', 'Türker Proje Gayrimenkul ve Yatırım Geliştirme', false),
  ('TURSG', 'Türkiye Sigorta', true),
  ('UCAYM', 'Üçay Mühendislik Enerji ve İklimlendirme Teknolojileri', false),
  ('UFUK', 'Ufuk Yatırım', false),
  ('ULAS', 'Ulaşlar Turizm', false),
  ('ULKER', 'Ülker Bisküvi', true),
  ('ULUFA', 'Ulusal Faktoring', false),
  ('ULUSE', 'Ulusoy Elektrik', false),
  ('ULUUN', 'Ulusoy Un', false),
  ('UNLU', 'Ünlü Yatırım Holding', false),
  ('USAK', 'Uşak Seramik', false),
  ('USHOL', 'Us Yatırım Holding', false),
  ('VAKBN', 'Vakıfbank', true),
  ('VAKFA', 'Vakıf Faktoring', false),
  ('VAKFN', 'Vakıf Finansal Kiralama', false),
  ('VAKKO', 'Vakko Tekstil', false),
  ('VANGD', 'Van Et Entegre', false),
  ('VBTYZ', 'VBT Yazılım', false),
  ('VERTU', 'Verusaturk Girişim Sermayesi Yatırım Ortaklığı', false),
  ('VERUS', 'Verusa Holding', false),
  ('VESBE', 'Vestel Beyaz Eşya', false),
  ('VESTL', 'Vestel Elektronik', true),
  ('VEYAS', 'Türker Vangölü Enerji', false),
  ('VKFYO', 'Vakıf Menkul Kıymet Yatırım Ortaklığı', false),
  ('VKGYO', 'Vakıf GYO', false),
  ('VKING', 'Viking Kağıt', false),
  ('VRGYO', 'Vera Konsept GYO', false),
  ('VSNMD', 'Vişne Madencilik', false),
  ('YAPRK', 'Yaprak Süt ve Besi Çiftlikleri', false),
  ('YATAS', 'Yataş Yatak', false),
  ('YAYLA', 'Yayla Agro Gıda', false),
  ('YBTAS', 'Yibitaş Yozgat', false),
  ('YEOTK', 'Yeo Teknoloji Enerji ve Endüstri', false),
  ('YESIL', 'Yeşil Yatırım Holding', false),
  ('YGGYO', 'Yeni Gimat GYO', false),
  ('YIGIT', 'Yiğit Akü Malzemeleri Nakliyat Turizm', false),
  ('YKBNK', 'Yapı Kredi Bankası', true),
  ('YKSLN', 'Yükselen Çelik', false),
  ('YONGA', 'Yonga Mobilya', false),
  ('YUNSA', 'Yünsa Yünlü Sanayi', false),
  ('YYAPI', 'Yeşil Yapı Endüstrisi', false),
  ('YYLGD', 'Yayla Agro Gıda', false),
  ('ZEDUR', 'Zedur Enerji', false),
  ('ZERGY', 'Zeray GYO', false),
  ('ZGYO', 'Z GYO', false),
  ('ZOREN', 'Zorlu Enerji', true),
  ('ZRGYO', 'Ziraat GYO', false)
on conflict (kod) do nothing;

-- ── 3) RLS + GRANT (piyasa verisi: oturumlu herkes okur, service_role yazar)
alter table public.bist_hisse enable row level security;
alter table public.bist_hisse force  row level security;

drop policy if exists bist_hisse_select on public.bist_hisse;
create policy bist_hisse_select on public.bist_hisse
  for select to authenticated using (true);

revoke all on public.bist_hisse from public, anon, authenticated;
grant select on public.bist_hisse to authenticated;
grant all on public.bist_hisse to service_role;

-- ── 4) Tetikleyici (0076 edge_function_url + cron_headers deseni) ──────────
-- Ayrı secret açılmadı: 0129 emsali (kamu verisi okuyan cron, TÜFE çekimiyle
-- aynı secret). Yeni secret yasin'in iki sunucuda elle girmesini beklerdi.
create or replace function public.trigger_bist_hisse_katalog()
returns void
language plpgsql
security definer
set search_path = public, vault, net
as $$
begin
  perform net.http_post(
    url := public.edge_function_url('bist-hisse-katalog'),
    headers := public.cron_headers('inflation_fetch_cron_secret'),
    body := jsonb_build_object('source', 'cron'),
    -- İki TradingView + bir KAP isteği (30 sn zaman aşımı) + upsert.
    timeout_milliseconds := 90000
  );
end;
$$;

revoke all on function public.trigger_bist_hisse_katalog() from public, anon, authenticated;

-- Her gün TR 07:40 (04:40 UTC): seans öncesi; halka arzın ilk işlem günü
-- sabahı listede olur. Hafta sonu da koşar (ucuz; kod değişikliği hafta
-- sonu duyurulabiliyor).
select cron.unschedule(jobid) from cron.job where jobname = 'bist-hisse-katalog';
select cron.schedule('bist-hisse-katalog', '40 4 * * *',
  $$select public.trigger_bist_hisse_katalog()$$);

-- İki sunucu birebir; tek bilinçli fark cron `active` (0119 kuralı).
do $$
begin
  if exists (select 1 from cron.job where jobname <> 'bist-hisse-katalog')
     and not exists (select 1 from cron.job where jobname <> 'bist-hisse-katalog' and active) then
    perform cron.alter_job(job_id := jobid, active := false)
       from cron.job where jobname = 'bist-hisse-katalog';
    raise notice '0139: projede tum cron isleri kapali — bist-hisse-katalog da kapali kuruldu.';
  end if;
end $$;

-- ── 5) Doğrulama ────────────────────────────────────────────────────────────
do $$
begin
  if not has_table_privilege('authenticated', 'public.bist_hisse', 'select') then
    raise exception '0139: authenticated SELECT grant eksik';
  end if;
  if has_table_privilege('authenticated', 'public.bist_hisse', 'insert')
     or has_table_privilege('authenticated', 'public.bist_hisse', 'update')
     or has_table_privilege('authenticated', 'public.bist_hisse', 'delete') then
    raise exception '0139: authenticated yazma yetkisi verilmemeli';
  end if;
  if has_table_privilege('anon', 'public.bist_hisse', 'select') then
    raise exception '0139: anon erisimi olmamali';
  end if;
  if not exists (select 1 from pg_class c join pg_namespace n on n.oid = c.relnamespace
       where n.nspname = 'public' and c.relname = 'bist_hisse'
         and c.relrowsecurity and c.relforcerowsecurity) then
    raise exception '0139: RLS/FORCE RLS acik degil';
  end if;
  if has_function_privilege('authenticated', 'public.trigger_bist_hisse_katalog()', 'EXECUTE')
     or has_function_privilege('anon', 'public.trigger_bist_hisse_katalog()', 'EXECUTE') then
    raise exception '0139: trigger_bist_hisse_katalog istemciden cagrilabilir olmamali';
  end if;
  if not exists (select 1 from cron.job where jobname = 'bist-hisse-katalog') then
    raise exception '0139: bist-hisse-katalog cron isi kurulmadi';
  end if;
  if (select count(*) from public.bist_hisse where aktif) < 450 then
    raise exception '0139: seed eksik';
  end if;
  raise notice '0139 tamam: BIST hisse katalogu, seed ve cron kuruldu.';
end $$;
